- types/stream-chat/index.d.ts
> Fix missing and wrong declarations

- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
> Add mentioned users to message type

- changelog.md
- src/channel.js
- src/client.js
- test/notifications.js
- test/serverside.js
- test/webhook.js
> Mark read more

- changelog.md
- src/client.js
- test/gdpr.js
> GDPR improvements

- test/query_users.js
> [CHAT-537] enable autocomplete tests

- src/channel.js
- src/channel_state.js
Reactions in threads were not managed in threads. This PR should fix that.
> fix reactions in threads

- test/serverside.js
> more tests on check push endpoint

- test/serverside.js
> also check for channel in push_test

- test/serverside.js
- test/test.js
> Fix tests user id

- package.json
I opened the npm package here: https://www.npmjs.com/package/stream-chat and was unable to locate where the repository was hosted. So this is to add the repository link to the package info panel.
> chore: update package repo link

- test/serverside.js
Tests for the push versioning system
> [CHAT-581] expired tokens

- src/channel.js
> Fix user id property name for member.updated event callback

- test/serverside.js
Small tweak to push test test to make it pass
> fix push test test

- test/serverside.js
> [CHAT-647]make created_at and updated_at reserved fields

- src/connection.js
> Improving the reconnection logic

- test/presence.js
> test watcher counts

- test/presence.js
- test/test.js
> test anon watcher list

- src/client.js
- src/connection.js
> [Chat-633] add x stream client info to websocket client connections

- test/delete_channel.js
> [CHAT-655] assert channel created_by to null not undefined

- package.json
While fixing issues with stream-chat-react I stumbled upon this issue. Simple fix.
> fix security issue with axios

- test/presence.js
- test/query_users.js
- test/test.js
> tests for user.id in autocomplete

- test/notifications.js
> [CHAT-676]ensure that replies dont increase unread counts

- test/threads.js
> Add tests for get replies pagination

- src/channel.js
- src/channel_state.js
> Reconnection thread issue

- test/channels.js
> [CHAT-680]sort by unread/has_unread

- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
> Syncing ts declaration file

- package.json
- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
- yarn.lock
> Fixing ts declaration file

- src/client.js
- test/channels.js
- types/stream-chat/index.d.ts
> [Chat-688] hard delete messages

- test/channels.js
> support $exists operator

- test/presence.js
> do not set created_by_id for client side requests

- test/presence.js
> do not set created_by_id for client side requests II

- test/presence.js
> do not set created_by_id for client side requests in Count Guest test

- test/channels.js
> improve sort by unread tests

- test/gdpr.js
- test/test.js
> [CHAT-687]ensure that deleted messages have type==deleted

- test/gdpr.js
> remove debug code

- test/channels.js
- test/presence.js
- test/query_users.js
- test/threads.js
This PR will fix some issues with tests for travis-ci
> Fix for qa-tests  

- src/client.js
Need some extra logs to debug homeis issue where they keep running into error once in a while (but quite frequently)
> Added some error logs

- src/channel.js
- src/client.js
- src/connection.js
- test/serverside.js
> fix test for push test

- test/serverside.js
> ensure that unread counts are properly initialised

- test/query_users.js
> test/query_users: add mutes for server side check

- test/presence.js
> await on disconnect/stopwatch

- test/webhook.js
> Add mute and unmute webhook tests

- test/test.js
better test for anonymous users
> skip tests

- test/moderation.js
> Add test for unmute event

- src/channel.js
- src/client.js
- src/connection.js
- test/serverside.js
- test/test.js
> Channel hide

- test/invites.js
- test/test.js
> [Chat-657] support query invites

- test/invites.js
[Chat-657] support query invites
> CHAT-657-support-query-invites

- test/webhook.js
> add tests for webhook channel type and id

- test/channels.js
> [CHAT-776] members $nin test

- src/client.js
Fixing file upload thanks to @vishalnarkhede
> fix file upload issue

- test/presence.js
- test/utils.js
> Improvement for watcher count test

- test/channels.js
> Update test for channel members to stop randomly failing

- types/stream-chat/index.d.ts
> CHAT-669: Adding types for ChannelData

- test/serverside.js
> [chat-811]add test for default role

- package.json
- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
- yarn.lock
Fixing some types in client and connection.js Also fixing issue reported in https://github.com/GetStream/stream-chat-js/issues/145
> CHAT-669: Fixing types for client and connection

- test/test.js
> Add test for banned field

- package.json
- test/test.js
- yarn.lock
> opengraph tests

- test/serverside.js
> Fix test for missing roles

- src/client.js
- test/serverside.js
Add tests and docs for Firebase data template
> [CHAT-804] feature/add-firebase-data-template

- test/serverside.js
> skip broken test

- test/test.js
> skip search users test

- test/serverside.js
> Fix tests for apn after bugfix

- test/serverside.js
Reverts GetStream/stream-chat-js#165
> Revert "Fix tests for apn after bugfix"

- test/serverside.js
Reverts GetStream/stream-chat-js#168
> Revert "Revert "Fix tests for apn after bugfix""

- test/test.js
> ensure that messages sent my muted users don't increase unread counts

- test/test.js
> basic banned query test

- .eslintrc.json
- package.json
- src/channel.js
- src/client.js
- yarn.lock
Add sonarjs to find more code smells
fixes #110
Patch handles the issues but set cognitive complexity to 30 since default (15) requires a bigger refactoring.
> Add sonarjs for linting

- .travis.yml
> Run lint on travis

- package.json
- yarn.lock
Bump sonarjs: some fixes to rules and new rules.
> Bump sonarjs

- test/test.js
> Add tests for non-existing pager for messages and members

- src/events.js
- test/webhook.js
Send channel.created to webhook
> channel.created webhook test

- src/channel.js
- types/stream-chat/index.d.ts
> add optional message to addMembers and removeMembers channel methods

- test/channels.js
- test/invites.js
- test/serverside.js
- types/stream-chat/index.d.ts
Reverts GetStream/stream-chat-js#188
> Revert "Chat 879 system messages 2"

- src/channel.js
- test/presence.js
- types/stream-chat/index.d.ts
PR in react sdk - https://github.com/GetStream/stream-chat-react/pull/91
PR in RN sdk - https://github.com/GetStream/stream-chat-react-native/pull/92
> CRNS-32: Handling channel-truncated event

- test/test.js
> Skip enrichment test

- package.json
- test/test.js
This is for the queryUser endpoint only. Feature request from Imgur (#49 from their issue tracker)
> Return user.banned with the user payload

- src/client.js
- types/stream-chat/api-response-tests/response-generators/channel-search.js
- types/stream-chat/api-response-tests/response-generators/message.js
- types/stream-chat/api-response-tests/response-generators/moderation.js
* unused import (imported but not used)
* constant condition (variable is already type checked)
> Remove some unnecessary

- test/channels.js
This PR adds tests over a new query/filter parameter.
> [CHAT-861] Add Tests For 'last_updated' Parameter

- .travis.yml
> Add new node versions - 12 and 13

- types/stream-chat/api-response-tests/response-generators/channel.js
- types/stream-chat/api-response-tests/response-generators/client.js
- types/stream-chat/api-response-tests/response-generators/moderation.js
> Drop some unused requires

- test/moderation.js
- test/serverside.js
- types/stream-chat/api-response-tests/response-generators/channel-type.js
- types/stream-chat/api-response-tests/response-generators/event.js
- types/stream-chat/api-response-tests/response-generators/moderation.js
- types/stream-chat/api-response-tests/response-generators/reaction.js
- types/stream-chat/test-stream-chat.ts
> More cleanup of unused

- types/stream-chat/api-response-tests/index.js
- types/stream-chat/index.d.ts
> Set proper response type of the set user function

- types/stream-chat/api-response-tests/index.js
- types/stream-chat/api-response-tests/response-generators/update-users.js
- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
https://github.com/GetStream/stream-chat-js/issues/210
> CRNS-53: Fixing/updating types for partialUpdateUser function

- package.json
- test/channel_permissions.js
- test/serverside.js
- types/stream-chat/api-response-tests/response-generators/moderation.js
- types/stream-chat/test-stream-chat.ts
* drop no lint that prevents prettier run on test file
* also run dtslint on test file
* drop unused code
> More type test cleanup

- test/channels.js
- test/delete_channel.js
- test/gdpr.js
- test/invites.js
- test/moderation.js
- test/presence.js
- test/query_users.js
- test/reactions.js
- test/test.js
- test/threads.js
Swap promise implementation without disabling lint
> Improve promise swap 

- package.json
- types/stream-chat/test-stream-chat.ts
- yarn.lock
* Uncomment one type test and fix it.
* Bump dtslint too
> Bump dtslint, improve two tests

- types/stream-chat/index.d.ts
> fix types for sendFile and sendImage to accept buffer

- types/stream-chat/index.d.ts
Fixed spelling mistake in type definition.
> fixed spelling mistake in type definition

- test/channels.js
> skip unread asc tests

- test/channels.js
> [CHAT-951]add ability to query by frozen

- test/channels.js
> more frozen tests

- test/gdpr.js
> add test for hard delete and replies on channel

- test/channels.js
> implement $ne operator for reserved and  custom fields.

- rollup.config.js
- src/base64.js
This will fix the browser bundle. I will file a separate PR for updating rollup plugins.
Fixes https://github.com/GetStream/stream-chat-js/issues/259
> Fixing browser bundle

- test/test.js
> Skip 404 error test for DeleteDevice

- src/connection.js
- test/test.js
> Increment wsId when ws is disconnected manually

- CHANGELOG.md
> Updating changelog for 1.3.4

- test/serverside.js
> [CHAT-896] Update tests match to refactored code

- test/serverside.js
Reverts GetStream/stream-chat-js#268
> Revert "[CHAT-896] Update tests match to refactored code"

- test/serverside.js
> Adjust tests to new push code

- src/channel.js
- src/channel_state.js
- src/client.js
- src/events.js
- test/moderation.js
- types/stream-chat/index.d.ts
> mute channel

- src/channel.js
- src/channel_state.js
- src/client.js
- test/moderation.js
- test/webhook.js
> implement muteStatus/ increase test coverage

- src/channel_state.js
- types/stream-chat/index.d.ts
> Updating removeMessage function to handle threads

- test/channels.js
- test/reactions.js
- test/test.js
Replaces checks for large payloads with the correct status code. This PR depends on [#803](https://github.com/GetStream/chat/pull/803)
> Update Status Codes Checks for Large Payload

- test/channels.js
> ensure that deleted channels do not return messages

- test/test.js
> fix sort order when paginating with id_gt/id_gte

- src/client.js
- types/stream-chat/api-response-tests/index.js
- types/stream-chat/api-response-tests/response-generators/message.js
- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
gracefully rename updateUsers into upsertUsers (alias added)
@vishalnarkhede if you are OK with this, can you update typescript and also add deprecation info to jsdoc?
> add alias for upsertUser[s]

- types/stream-chat/index.d.ts
> Fix a typo in attachment type

- test/notifications.js
> bump max unread count to 255

- test/test.js
Small adjustment to do more page request and adapt indexes to prevent off by one errors.
> Page and index adjustment for member pagination

- package.json
- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
> Updating typescript to include permissions constants

- src/client.js
PR removes hard limit from user's data size to allow server check for it and respond accordingly.
> Remove User's Data Size Check

- src/channel.js
- src/channel_state.js
- test/channels.js
- test/test.js
- types/stream-chat/index.d.ts
Add support for upcoming new field from channel responses. @vishalnarkhede if you are happy with this can you take care of typescript defs?
> Populate channel state with the new membership field

- test/test.js
PR adds a test for large user custom data fields (over 5 KB)
#289 
https://github.com/GetStream/chat/pull/937
> Add Test For User Custom Data Size

- types/stream-chat/index.d.ts
> add types for getConfig return

- test/multitenant.js
> Allow changing team for server side auth requests

- test/test.js
> fix hidden channels test

- test/channels.js
> wait for message new event

- test/channels.js
> Fix non selective tests

- test/channels.js
> fix undefined

- package.json
- types/stream-chat/index.d.ts
- yarn.lock
> update type for verifyWebhook

- test/channels.js
> add test for paginating after the first channel message

- types/stream-chat/index.d.ts
Fixes: https://github.com/GetStream/stream-js/issues/258
> fix conflicting typescript namespace

- test/multitenant.js
> increase tests coverage for multi-tenant channel search

- src/channel.js
- test/silent.js
> add silent messages support

- src/client.js
- src/connection.js
- src/index.js
- src/token_manager.js
- src/utils.js
- test/connection.js
- test/multitenant.js
- test/test.js
- test/token_manager.js
- test/utils.js
- types/stream-chat/api-response-tests/index.js
- types/stream-chat/index.d.ts
```js
client.setUser({id: 'vishal'}, 'token');
```
```js
client.setUser({id: 'vishal'}, async () => {
// const token = await api.fetchToken();
return token;
});
```
- New class - `TokenManager`, which will be a common place to access token from for client and connection class.
- When ws connection fails with error code `40`, the token will be refreshed using tokenProvider function (given to `setUser` function) and connection request will be retried.
- When http request fails with error code `40`, the token will be refreshed using tokenProvider function (given to `setUser` function) and connection request will be retried.
> Handling token expiration

- src/client.js
Disable presence by default
Fixed #218
> Disable presence by default for user query

- src/client.js
- test/webhook.js
- types/stream-chat/index.d.ts
also update flag function signature to allow server side flag
> add tests for message.{flagged,unflagged} webhook events

- package.json
- rollup.config.js
- src/client.js
- test/channel_permissions.js
- test/channels.js
- test/connection.js
- test/delete_channel.js
- test/gdpr.js
- test/invites.js
- test/moderation.js
- test/multitenant.js
- test/notifications.js
- test/presence.js
- test/query_users.js
- test/reactions.js
- test/serverside.js
- test/test.js
- test/threads.js
- test/webhook.js
- test/x-setup.js
- types/stream-chat/api-response-tests/response-generators/channel-search.js
- types/stream-chat/api-response-tests/response-generators/channel-type.js
- types/stream-chat/api-response-tests/response-generators/channel.js
- types/stream-chat/api-response-tests/response-generators/client.js
- types/stream-chat/api-response-tests/response-generators/event.js
- types/stream-chat/api-response-tests/response-generators/message.js
- types/stream-chat/api-response-tests/response-generators/moderation.js
- types/stream-chat/api-response-tests/response-generators/reaction.js
- types/stream-chat/api-response-tests/response-generators/update-users.js
- yarn.lock
Reverts GetStream/stream-chat-js#323
Given version of UUID doesn't work well with react-native - https://github.com/uuidjs/uuid#getrandomvalues-not-supported
> Revert "bump uuid to v8"

- test/multitenant.js
> add test for reading channels without specifying the team

- src/channel.js
> Fixing read status issue

- CHANGELOG.md
Update CHANGELOG dates and versions around 1.1.7, 1.1.8, 1.2.0
> Fix CHANGELOG versions and dates

- test/query_members.js
* remove unnecessary to make test a bit faster
> Drop unnecessary/simplify in query members

- test/channels.js
add test for https://github.com/GetStream/chat/pull/1077
> add channels.name autocomplete test

- test/hooks.js
- test/presence.js
Add tests for the upcoming message send hook feature
> before message send hook

- types/stream-chat/index.d.ts
Should be CommandResponse[], not CommandVariant[]
> fix: type of channel.getCommands

- test/channels.js
> add tests for search by message type

- test/test.js
> add tests for matching messages with empty text

- .github/workflows/size.yml
we had added in stream-js, why not here?
> Add size comparison action

- test/webhook.js
> add webhook tests for users created/updated using setUser

- package.json
- yarn.lock
bump version for `@types/seamless-immutable` to 7.1.12 so it matches stream-chat-react.
> Update types for seamless-immutable, move types to devDependencies

- .github/workflows/ci.yml
- package.json
> drop support for node 11,13

- types/stream-chat/index.d.ts
- types/stream-chat/test-stream-chat.ts
- StreamChat.updateMessage now has optional user parameter (implementation checks for null/undefined).
- ChannelState Typing events now extend Event
- MessageToImmutable takes MessageResponse, not Message
> Minor type fixes

- src/connection.js
> Changing ws issue logs to warn level

- test/serverside.js
> Add updating default channel type

- src/client.js
Introducing setter function for userAgent, so that we can use it to set custom userAgent from Chat component of stream-chat-react and stream-chat-react-native. This will help us track the stats of which sdks and version are consumers using.
> Setter for userAgent

- test/serverside.js
small change, just split up the tests into 3 cases
> Split up tests for Custom Command Url appconfig

- src/events.js
> enable channel.visible event

- test/query_members.js
> [Chat-1090] allow search by member last_active

- test/query_members.js
> [Chat-1090] allow search by last active in query members[fix tests]

- test/query_members.js
> [CHAT-1099] support query channels by member.user.name

- test/channels.js
> [CHAT-1116] queryChannels member_limit

- src/channel.ts
- src/channel_state.ts
- src/client.ts
- src/connection.ts
- src/types.ts
- ts-test/index.js
- ts-test/response-generators/client.js
> Typescript backwards compatibility

- src/channel.ts
UserID should be optional on these two functions.
> make reactions userid optional

- CHANGELOG.md
> v2.1.1 update changelog

- .github/workflows/ci.yml
- src/client.ts
- ts-test/index.js
> Removed un-used last_message_ids from queryChannels api call

- CHANGELOG.md
- src/channel.ts
Update to 2.0.0 Changelog with description on Event type change.
> update changelog and doc comment

- src/types.ts
- ts-test/unit-test.ts
> Fixing ts for ChannelFilters

- src/client.ts
> Fixing race condition issue with with options (warmUp) request

- test/query_members.js
> Add name sorting into query members

- package.json
Re-add @types/seamless-immutable for TS
> move @types/seamless-immutable

- package.json
> move @types/jsonwebtoken

- src/client.ts
- src/types.ts
- test/moderation.js
> Blocklist API support

- src/channel.ts
- test/test.js
> fix channel.keystroke failing for first event

- test/serverside.js
> fix for custom_action_handler_url test

- test/query_users.js
> Fix non-deterministic autocomplete queryusers test

- src/types.ts
Adjust name to match normal pattern
> T to UserType

- test/integration/test.js
> test: fix wrong err msg

- test/integration/channels.js
> [CHAT-1283] make sure members $in won't return channels for deleted users

- src/client.ts
- src/types.ts
- test/typescript/unit-test.ts
Modify members query filter options and update message type
> fix #480: Modify members query and make message.id optional

- test/integration/translate.js
Second translation can be different sometimes
> Fix flaky translation test

- test/integration/moderation.js
make image_moderation_enabled a configurable app setting: https://stream-io.atlassian.net/browse/CHAT-1294
> [CHAT-1294] create image_moderation_enabled App setting

- src/client.ts
> doc: improve new channel without id

- src/channel.ts
> optional parent_id in stopTyping

- src/events.ts
- src/types.ts
- test/integration/invites.js
Depends on https://github.com/GetStream/chat/pull/1434/files
Closes #416
> Adding support for event notification.invite_rejected

- src/channel.ts
- src/client.ts
- src/types.ts
- src/utils.ts
- test/typescript/unit-test.ts
- test/unit/sort.js
- test/unit/utils.js
This PR adds ability to provide sort configuration using array of objects to guarantee order of the fields.
> [CHAT-1314] Added ability to provide array of sort directions

- src/types.ts
> added enforce_unique_usernames to AppSettingsAPIResponse

- test/typescript/response-generators/moderation.js
> ts tests cleanup bucket list

- src/types.ts
> add custom_events to CreateChannelOptions type

- src/client.ts
- test/integration/push_test/push-test-credentials.json
- test/integration/serverside.js
- test/integration/x-setup.js
> Add push v2 config tests

- src/channel.ts
> fix: reset unreadCount on channel truncate event

- src/types.ts
> Add push v2 config types

- test/integration/channels.js
- test/integration/test.js
> Ensure 400 if no searchable

- src/client.ts
- src/types.ts
> recoverStateOnReconnect option and type UpdatedMessage

- src/channel.ts
> Update read state when new message is sent

- src/types.ts
- test/typescript/index.js
- test/typescript/response-generators/client.js
> Add custom_action_handler_url & enforce_unique_usernames to AppSettings

- test/integration/serverside.js
> Ensure device cache is not cleared

- test/integration/multitenant.js
> [CHAT-1462] fix controller names

- CHANGELOG.md
- test/integration/presence.js
Sometimes a notification is delivered, which fails the test. This should fix it.
> Fix presence test

- src/types.ts
> add webhook related types to MessageResponse

- test/integration/presence.js
> Fix presence integration test

- src/channel.ts
- src/channel_state.ts
> adding reaction.updated handler based on the new enforce_unique parameter

- test/integration/channels.js
> Skip concurrent partial channel update

- test/integration/test.js
> Enrich channel in get message

- test/integration/test.js
> [CHAT-1445] add support for pagination by date

- test/integration/channels.js
> [CHAT-1347] search by mentioned users

- src/types.ts
> Add types for quoted messages

- src/client.ts
- src/index.ts
- src/utils.ts
Adjusting types and adding type guard to reflect OwnUserResponse as a possible type on the client.user variable.
> add isOwnUser type guard and add OwnUser to Client User type

- src/types.ts
Add to types
total_unread_count?: number;
unread_channels?: number;
> add total_unread_count and unread_channels to event type

- test/integration/channels.js
All tests are being ignored right now :)
> Removed .only from the tests

- src/types.ts
- test/typescript/index.js
- test/typescript/response-generators/message.js
> Adding thread_participants to MessageResponse type

- .github/workflows/ci.yml
> Speedup ci

- src/types.ts
added various missing type definitions
> added missing type defs

- test/integration/channels.js
Apply sanitization to searchmessage queries
> QA tests for message search sanitization

- .github/workflows/size.yml
- src/types.ts
> Channel query date parameters

- src/connection.ts
> fix comment on retry interval range

- docs/userToken.md
> update token provider doc

- src/client.ts
- test/unit/client.js
> feat: connectUser works for consecutive calls

- README.md
- docs/logging.md
- docs/userToken.md
> doc: use StreamChat.getInstance

- src/client.ts
> Add missing options to gdpr

- src/channel.ts
- test/integration/channels.js
- test/integration/notifications.js
- test/integration/reactions.js
- test/integration/sync.js
- test/typescript/response-generators/reaction.js
Since immutable is breaking, it's right moment to add more breaking changes such that we switch `sendReaction` similar to `sendMessage` and can have different/new options.
> Introduce options for sendReaction

- src/channel.ts
- test/unit/channel_state.js
- test/unit/test-utils/getClient.js
> Set isUpToDate to false, when channel is disconnected

- src/types.ts
Organize types added recently into appropriate categories and re-ABC them within the categories
> organize types and abc

- src/types.ts
Reverts GetStream/stream-chat-js#627
> Revert "organize types and abc"

- src/client.ts
- src/types.ts
- test/typescript/index.js
- test/typescript/response-generators/client.js
> [CHAT-1622] add support for query by banned users

- src/channel_state.ts
This PR adds reaction sync for pinned messages in channel state
> Support reactions sync for pinned messages in channel state

- src/types.ts
This reverts commit c038beac28d9381313d30e6e2ea1da7cba6a018e.
> Revert "Revert "organize types and abc""

- src/client.ts
- src/types.ts
- test/unit/client.js
> Handle given base url from options

- test/typescript/response-generators/channel.js
> fix: test-types __html

- src/client.ts
- src/types.ts
- test/typescript/unit-test.ts
Adding types to 'type' on message.
> Add message types

- src/client.ts
> [CHAT-1721] overwrite local ws port

- src/types.ts
> Add cooldown to channel response type

- src/channel_state.ts
- src/client.ts
- src/types.ts
- test/unit/channel.js
- test/unit/channel_state.js
- Delete user messages when you receive `user.deleted` event
- Update `message.user` object, when `user.updated` event is received
> CRNS-321: Update message references for deleted or updated users

- .github/workflows/ci.yml
> run CI on node 16

- src/types.ts
This PR adds the `disabled` field to the `ChannelResponse` type.
> [CHAT-1652] Add disabled field

- src/client.ts
- Make passing revoke date for application level revoke mandatory.
> make passing revoke date in application level revoke token mandatory

- src/types.ts
> Fixing some backend types

- src/client.ts
> Fix: undefined active channel on mute/unmute

- src/client.ts
- src/types.ts
> added segment api crud methods

- src/types.ts
- AppSettings type support `multi_tenant_enabled` attribute
> Fix #701: AppSettings type multi_tenant_enabled

- src/types.ts
- test/typescript/index.js
- test/typescript/response-generators/client.js
- test/typescript/utils.js
> add multitenancy event type and test

- CHANGELOG.md
> Changelog 3.12.0

- src/types.ts
This PR adds new `grants` field to AppSettings
> [CHAT-1994] Add grants field to AppSettings

- src/client.ts
- src/types.ts
> Campaign crud 

- src/client.ts
- src/connection.ts
- src/types.ts
- test/unit/client.js
- test/unit/connection.js
> setLocalDevice push config via WS

- src/client.ts
> fixing user update logic

- src/types.ts
> [CHAT-1936] campaign name and desc

- src/client.ts
- src/types.ts
> add docs for queryChannels skipInitialization param

- src/types.ts
> queryChannel support user_id

- src/types.ts
> [CHAT-1870] Add team filter for query flagged messages

- src/client.ts
So that full segment or campaign could be passed to updates.
> Campaign update namespace

- src/client.ts
- src/connection.ts
- test/unit/connection.js
based on https://github.com/GetStream/stream-chat-js/pull/758
mostly a fix and not really a breaking change since it's correcting the flag behavior
also these flags are for internal use only
> consolidate isConnecting flag

- src/client.ts
- src/types.ts
> [CHAT-2294] GetTask endpoint to retrieve async task results

- yarn.lock
Reverts GetStream/stream-chat-js#768
> Revert "Bump axios from 0.21.1 to 0.21.2"

- src/client.ts
- src/connection.ts
- src/insights.ts
- src/types.ts
- src/utils.ts
- test/unit/connection.js
- test/unit/test-utils/getClient.js
- Adds ability to send insights about failures from client
Added extra property to StreamChat constructor's options object:
```tsx
const client = StreamChat.getInstance('apikey', { enableInsights: true })
```
> WS Insights

- src/client.ts
- src/types.ts
Customers need a way to manage quote flag per channel type from dashboard
- Expose `quotes` boolean as part of `ChannelConfigFields`
> [CHAT-1796] expose quotes flag

- src/index.ts
> export all from insights file

- src/insights.ts
this is necessary so we can distinguish insights from different client instances
-
> [CJS-11] inject instance_client_id 

- docs/logging.md
- src/client.ts
- test/typescript/unit-test.ts
> [CJS-12] use chat.stream-io-api.com as baseURL

- src/types.ts
transfer channel ownership while hard-deleting users through new_channel_owner_id option
> [CHAT-2437] Transfer channel ownership

- src/client.ts
> don't overwrite headers

- src/channel.ts
- Support hard delete items when truncating a channel
> [CHAT-2445] Add hardDelete option to truncate channel

- .eslintrc.json
- .prettierrc
- README.md
- rollup.config.js
- src/base64.ts
- src/channel.ts
- src/channel_state.ts
- src/client.ts
- src/connection.ts
- src/insights.ts
- src/permissions.ts
- src/signing.ts
- src/token_manager.ts
- src/types.ts
- src/utils.ts
- test/typescript/index.js
- test/typescript/response-generators/channel.js
- test/typescript/response-generators/client.js
- test/typescript/unit-test.ts
- test/typescript/utils.js
- test/unit/channel.js
- test/unit/channel_state.js
- test/unit/client.js
> prettier: increase line width to 120char

- src/channel.ts
- src/channel_state.ts
- src/client.ts
- src/client_state.ts
- src/connection.ts
- src/signing.ts
- src/token_manager.ts
- src/types.ts
- src/utils.ts
- test/typescript/unit-test.ts
> types: UR alias UnknownType

- src/types.ts
`ChannelOptions` type definition is now in sync [REST API](https://getstream.io/chat/docs/rest/#channels-querychannels)
-
> fix: ChannelOptions type definition

- .github/workflows/ci.yml
> CI: run on node v17

- package.json
- src/client.ts
- yarn.lock
high severity security issue https://github.com/advisories/GHSA-cph5-m8f7-6c5x
> Chore: upgrade axios to v0.22

- src/client.ts
- src/types.ts
> Breaking Change: Remove BanUserOptions deprecated user & user_id types

- src/client.ts
- test/unit/connection.js
> Fix: Remove unused fileds in WS JOSN payload

- src/client.ts
- src/connection_fallback.ts
- test/unit/client.js
> Fix Longpoll

- src/client.ts
- src/types.ts
- test/unit/client.js
> Feat: transport.changed event

- src/connection_fallback.ts
- test/unit/connection_fallback.js
> Test: connection fallback

- src/types.ts
- Add user push notification settings
> Add user push notification settings

- src/types.ts
> Types: add missing level attribute to PermissionAPIObject

- .github/workflows/ci.yml
> CI: improve cache restore

- src/types.ts
> Types: Fix ListCommandsResponse optional timestamps

- .github/CODEOWNERS
Removing myself from codeowners since I no longer own the code x)
> Remove @vicnicius from codeowners

- .github/workflows/lint.yml
- .github/workflows/type.yml
- .github/workflows/unit.yml
- README.md
> Chore: Skip CI on master branch

- README.md
- src/types.ts
remove imgur as its not supported anymore
> feat: remove imgur from commands

- src/types.ts
This PR adds support for a new `permission.tags` API field
> Add permission tags support

- src/channel.ts
- Fix flickering and out-of-order events on truncate.channel with system message
> [CJS-13] Fix flickering and out-of-order events on truncate.channel with system message

- .github/workflows/initiate_release.yml
fix the with/script section of the yaml
> ci: fix initiate_release job once again

- src/events.ts
> fix: add channel.kicked event

- src/client.ts
- Add `_unblockMessage` private function
Chat MR: https://github.com/GetStream/chat/pull/2969
> feat: add unblockmessage

- src/client.ts
- src/types.ts
Also, drop huawei data template which was never used.
> feat: add xiaomi push provider

- src/events.ts
- src/types.ts
> fix: added transport.changed event to event map

- .github/CODEOWNERS
> Add madsroskar as codeowner

- src/channel.ts
> fix: ignore unread count for thread replies

- src/client.ts
- src/types.ts
- Added `_queryFlags` function and some type definitions that are needed for flags.
> feat(moderation): add _queryFlags function

- src/channel.ts
> feat: add id_around support for replies

- src/types.ts
Added fields for the new reminders feature
> feat: add reminders feature

- src/types.ts
> feat(truncate): add truncated by options

- src/types.ts
Fixes #915 
- Added appropriate type to ChannelSort.
> fix: types of fields in ChannelSort

- test/typescript/index.js
> docs: missing fullstop

- src/events.ts
https://github.com/GetStream/stream-chat-js/issues/965
> feat(eventmap): add user.unread_message_reminder

- src/types.ts
Add type definition to NNBB related field details on error response.
> refactor: add isErrorResponse type to APIErrorResponse details field

- src/types.ts
- Add `first_reporter` field to the `FlagReport` type
> feat: add `first_reporter` field to the `FlagReport` type

- src/channel.ts
- src/client.ts
- src/types.ts
Adds support for new ext_video endpoints (not live yet!)
> feat(video): video endpoints

- src/types.ts
> fix: missing app setting types

- src/channel.ts
- src/channel_state.ts
- test/unit/channel.js
- test/unit/channel_state.js
> fix: message update and delete events override own reactions

- CHANGELOG.md
> chore: add missing changelog

- src/channel.ts
- src/types.ts
Add pending messages request and response fields to sendMessage
- Add pending message flags to sendMessage
> feat: send pending messages

- src/types.ts
Add pending messages to channel response
-
> feat: pending messages in channel response

- src/channel.ts
- src/channel_state.ts
Include pending messages in channel state 
- Include pending messages in channel state
> feat: pending messages in channel state

- src/client.ts
- src/types.ts
- Add more types for StreamChat.sync function.
> feat: add more sync function types

- src/client.ts
- src/types.ts
> feat: get pending message with metadata

- src/channel.ts
- src/client.ts
- src/events.ts
Motive of this fix is the following issue https://github.com/GetStream/stream-chat-js/issues/869
- replaces console.warn instead throwing an error when event is not valid
> feat: replaces console.warn instead throwing error when event is not valid

- src/types.ts
> feat: async moderation config in app settings

- README.md
Addition of how to run the stream-chat-js lib. together with our SDKs. 
Currently is RN added.
-  dev mode in combination with our SDKs section addition
> docs: dev mode in combination with our sdks sec. add

- src/client.ts
- test/unit/client.js
setLocalDevice was checking for a stale wsconnection class to check if websocket was alive. This is not correct.
Thank you @vishalnarkhede 💯 
-
> fix: set local device's check for alive websocket connection

- src/channel.ts
Reverts GetStream/stream-chat-js#1064
> Revert "feat: allow optimistically added messages in local state"

- package.json
- yarn.lock
> fix: bump jwt v9

- src/channel.ts
- src/client.ts
> feat: do not delete the active channel if offlineMode is true

- src/channel.ts
- test/unit/channel.js
> fix: disallow pending message feature on client side

- src/client.ts
- src/types.ts
> fix: remove un-supported unread count api endpoint

- src/client.ts
- src/types.ts
- Add the option to exclude expired bans
> feat: add the option to exclude expired bans

- src/channel.ts
- src/types.ts
- Update last_read_message_id on message.read
> feat: update last_read_message_id on message.read

- src/client.ts
Escape url path parameter in getMessage.
> Escape url path params

- package.json
- yarn.lock
> feat: axios upgrade to v1

- src/client.ts
- src/types.ts
> fix: segment ts issue

- .husky/pre-commit
- .lintstagedrc.fix.json
- .lintstagedrc.json
- package.json
- yarn.lock
See https://github.com/GetStream/stream-chat-react/pull/2258.
> chore: use lint-staged for linting and fixes

- src/client.ts
- src/connection.ts
- src/events.ts
This reverts commit af8828bb99379c503f70520b17cc7b9c24b33c8b.
-
> revert: add new api for send a refresh-token (#1216)

- src/campaign.ts
- src/client.ts
- src/index.ts
- src/segment.ts
- src/types.ts
> feat: campaigns api

- src/client.ts
- src/types.ts
> fix: campaign typescript fixes

- src/campaign.ts
> fix: remove obsolete endpoints

- src/campaign.ts
- src/client.ts
> feat: added support for stop_at for campaign

- src/types.ts
> feat: add message attachment fields for voice messages

- src/types.ts
> fix: add thread_id to mark unread options typescript

- src/types.ts
> fix: fixing typescript for queryCampaigns sort option

- src/client.ts
- src/segment.ts
> fix: segment creation method signature fixes to allow optional id

- src/campaign.ts
- src/client.ts
- src/segment.ts
- src/types.ts
> fix: campaign instantiation without id

- src/client.ts
- src/types.ts
This is a new endpoint for querying reactions on a message based on msg_id.
You can filter by:
- user_id
- type
> feat: implement queryReactions

- src/types.ts
> [PBE-2573]: add support for notifications_muted in queryMembers

- src/types.ts
> fix: fix blockuser() vars naming

- src/types.ts
> feat: block user update, block_user response

- src/moderation.ts
- src/types.ts
> feat: moderation submit action endpoint

- src/client.ts
> [PBE-0] - Serverside support for polls

- src/channel.ts
- src/client.ts
Make sure the only allowed characters are part of the request URLs.
> fix: encode all the values interpolated to HTTP request URLs

- package.json
- yarn.lock
> chore(deps): bump ws from v7.4.4 to v7.5.10

- src/thread.ts
- test/unit/threads.test.ts
Restores soft-deletion of thread replies within Thread instance.
> fix(threads): restore reply soft-deletion

- src/channel.ts
- src/types.ts
Provide typescript support for querying by and upserting custom member fields.
https://stream-io.atlassian.net/browse/PBE-6326?atlOrigin=eyJpIjoiMWEzMmIzYTllOWNjNGYwNGI2ZTNjOWFmODhlYThhZGIiLCJwIjoiaiJ9
> feat: add typescript support for custom channel member fields

- src/token_manager.ts
🚂 https://github.com/GetStream/stream-video-js/pull/1578
> fix: fully reset token manager on user disconnect

- src/types.ts
Fix lint issues of the `types.ts` file.
> chore: lint fix types.ts

- src/channel.ts
Reverts behavior of the membership object initialization.
> fix: revert membership initialization behavior

- src/types.ts
- https://linear.app/stream/issue/CHA-344/support-channelteam-field-for-campaigns
- https://github.com/GetStream/chat/pull/7706
-
> feat: add team to channel template

- src/moderation.ts
- src/types.ts
> feat: multi tenancy moderation configuration support

- src/types.ts
- [fix: correct reviewqueue item filter: teams](https://github.com/GetStream/stream-chat-js/commit/2d909722428c54acf3b9eb30493bb8b2dfe4d60f)
> fix: correct reviewqueue item filter: teams

- src/types.ts
- [fix: add missing types for review queue filter](https://github.com/GetStream/stream-chat-js/commit/c33267068ea8d748d848813beb98747e8e366904)
> fix: add missing types for review queue filter

- src/client.ts
- src/types.ts
- test/unit/client.js
Context: https://getstream.slack.com/archives/C07EV8DFMRN/p1736844905674329
SDKs are expected to adopt the new format by the end of Q1
-
> feat: support new X-Stream-Client format

- src/types.ts
- https://linear.app/stream/issue/CHA-468/support-read-stats-for-campaigns
- https://github.com/GetStream/chat/pull/7991
- https://github.com/GetStream/docs-content/pull/198
-
> feat: expand campaign stats

- src/channel_manager.ts
- test/unit/channel_manager.test.ts
https://getstream.slack.com/archives/C06CF5TKRGA/p1740406130373979
-
> feat: add option to override channel.updated handler in ChannelManager

- rollup.config.js
> fix: add missing env variable in rollup config

- package.json
- scripts/bundle.mjs
- tsconfig.json
- yarn.lock
> chore(build): fix watch mode

- src/poll.ts
- src/thread.ts
- src/types.ts
> fix: adjust ChannelResponse, ChannelData & PollResponse

- src/client.ts
- src/connection.ts
- src/types.ts
- test/unit/connection.js
> fix: use URLSearchParams when building WS url

- src/channel.ts
- src/client.ts
- src/types.ts
- test/unit/draft.test.js
- Add Draft Messages API (thanks for the types @MartinCupela)
> feat: [CHA-375] add draft messages api

- package.json
- yarn.lock
Co-authored-by: Mason McAllaster @McAllaster
Closes: #1502
> chore(deps): upgrade @babel/runtime to v7.27.0

- src/messageComposer/attachmentManager.ts
- src/messageComposer/configuration/configuration.ts
- src/messageComposer/configuration/types.ts
- src/messageComposer/messageComposer.ts
- src/messageComposer/textComposer.ts
- test/unit/MessageComposer/attachmentManager.test.ts
- test/unit/MessageComposer/textComposer.test.ts
Add missing configuration parameters for AttachmentManager and TextComposer.
- acceptedFiles
- enabled
> feat: add missing configuration parameters for AttachmentManager and TextComposer

- src/messageComposer/middleware/textComposer/TextComposerMiddlewareExecutor.ts
- test/unit/MessageComposer/middleware/textComposer/TextComposerMiddlewareExecutor.test.ts
Avoid potential UI problems caused by delays in delivering the search results
> fix: prevent awaiting suggestion search results in TextComposerMiddlewareExecutor

- src/messageComposer/middleware/pollComposer/state.ts
- src/messageComposer/pollComposer.ts
- test/unit/MessageComposer/middleware/pollComposer/state.test.ts
> fix: prevent empty poll options and questions in composition

- src/messageComposer/middleware/pollComposer/state.ts
- src/messageComposer/pollComposer.ts
- test/unit/MessageComposer/middleware/pollComposer/state.test.ts
> fix: prevent poll creation with options with white spaces only

- src/client.ts
- test/typescript/index.js
- test/typescript/response-generators/channel-type.js
> fix: broken delete channel type api

- src/types.ts
Adding pending message hook support to `EventHooks` config request
- Added new enum `pending_message` to hook type
- Added timeout and callback mode
> feat: add pending message hook config

- package.json
- yarn.lock
Add latest version of form-data to master with security fixes
> chore(deps): upgrade form-data to version 4.0.4

- src/messageComposer/messageComposer.ts
- test/unit/MessageComposer/messageComposer.test.ts
Fix https://github.com/GetStream/stream-chat-react/issues/2786
> fix: keep pinned message data upon message editing

- src/utils.ts
> fix: consider locally filtered messages in message pagination params calculation

- src/types.ts
We are introducing a product-scoped hook config that allows configuration for specific products. When a product-scoped config is created, changes will not affect other products.
- Add `product` to `EventHook` type
> feat: add product to event hook request and response

- src/campaign.ts
- src/types.ts
> feat: (cha-1233) added sender visibility to campaign

- src/messageComposer/middleware/messageComposer/attachments.ts
Needed for this PR to work:
https://github.com/GetStream/stream-chat-react/pull/2842
> fix: add options to upload-in-progress warning notification

- src/types.ts
We are removing the feature flag, and making `count_messages` a feature that can be enabled/disabled per channel type.
-
> feat: (cha-1300) add count messages as feature

- src/messageComposer/textComposer.ts
- test/unit/MessageComposer/textComposer.test.ts
Fixes https://github.com/GetStream/stream-chat-react/issues/2847
> fix: normalize Windows CRLF newline sequence into LF line ending
