src/client.js

Adding the missing field - `reaction_counts` to reserved fields list to be removed from message while updating.

Removing reaction_counts from message since its a reserved field

---

.eslintrc.json
src/channel.js
src/client.js
src/signing.js
test/test.js

- The behaviour in `disconnect` was causing empty tokens to be sent to the API and crytpic error messages being generated.
- `Buffer()` is [deprecated due to security reasons](https://nodejs.org/de/docs/guides/buffer-constructor-deprecation/), so replace it accordingly and add eslint rule to prevent it from happening again

fixed error message and security warning

---

test/serverside.js

Unit test for bug:
When retrieving devices `serverside` for a user that has custom data the result is always empty

custom test for get devices cornercase

---

src/client.js

Start cleaner timer only after a connection is created and clear it when `disconnect` is called

only start cleanup timer when connection is up

---

src/client.js
test/query_users.js

Check was always true due to expression is evaluated first then `typeof` was returning `boolean` which true for the main boolean expression.
Added a guard for null check too. Since `typeof null === object` will return true which would break on property checks.
Other change is irrelevant - comes from prettier. 
I didn't add a test since it wasn't exported, if you guide me how to test it in terms of code layout, I'm happy to add more confidence.

Fix type check for readable stream

---

test/channels.js
test/query_users.js

Remove a console.log that breaks the output flow of tests (even on success)
There is unrelated change due to unfollowed prettier formatting before.

Remove a log that clutters test output

---

test/channels.js

Sometimes members may be in different order if created_at is the same, so test is failed

fix test when members have same created_at and may be in different order

---

types/stream-chat/index.d.ts

Made the `exp` value optional in the typescript definition.

Fixed `createToken` signature

---

types/stream-chat/index.d.ts

There was a small typo in the Typescript type definitions. `verifyWebHook` should be `verifyWebhook`, which is the actual exported method in the client.

Fix typo in types: verifyWebHook -> verifyWebhook

---

test/gdpr.js

Validation error is missing; we should also have validate tags for those fields
Sentry Issue: CHAT-FS
Stacktrace (most recent call first):
File "github.com/GetStream/chat/state/pg_redis_state.go", line 1043, in (*PGRedisState).DeleteUser
return nil, stack.Error("Can't do a hard delete without specifying mark_messages_deleted")
File "github.com/GetStream/chat/controllers/delete_user.go", line 60, in (*DeleteUser).Handle
removed, err := state.DeleteUser(r.Context(), chat.Auth().App(), userToRemove, request.MarkMessagesDeleted, request.HardDelete)
File "github.com/GetStream/chat/server/server.go", line 474, in (*Server).MakeHandler.func1
response, err := handler.Handle(ctx, w, r.WithContext(handleCtx))
File "github.com/GetStream/chat/server/cors.go", line 42, in CorsPreFlightMiddleware.func1 …

add test for deleteUser

---

.travis.yml
package.json
yarn.lock

dtslint is already in dev deps - this is just to bring it into attention.
After issues are fixed, we can enable it on travis.
Related to #210 #211.

Bump and run dtslint

---

package.json
src/base64.js
src/index.js
src/signing.js
test/test.js
types/stream-chat/index.d.ts
yarn.lock

If devToken is used on React Native, then `window.btoa` is not available (for obvious reasons). Thus we need some alternative ... hence adding a common method compatible with all clients.

CRNS-4: Updating dev token method (for compatibility with RN)

---

.travis.yml

Change install to script so that travis does only what we want.

Prevent travis test auto run

---

package.json

* correct licence SPDX record in package.json
* also add license into files so that users can check from installation if needed
fixes #181

Correct spdx record for license

---

src/connection.js

This is part of investigation of support ticket #1805
For some reason, our client tried to reconnect even though we just disconnected our ws connection. My suspicion is that call to ws.close results in error causing disconnect to fail. But to confirm this, we need some logs.

Adding some more logs for investigation

---

src/client.js
src/connection.js
test/test.js
types/stream-chat/index.d.ts

Fixes https://github.com/GetStream/stream-chat-js/issues/235

Fixing disconnect method

---

types/stream-chat/index.d.ts

fix types for channel.sendReaction

---

src/channel.js
test/test.js

Currently we throw error, if someone calls .off  on uninitialized channel. I think we should just allow it!!
Its simply a cleanup. E.g., in websocket … if you call .close  on closed connection, it still allows it. It does nothing, but doesn’t throw error as well.
In components (react or RN), if the component gets unmounted before .watch() , then it results into error because of this. We can handle it on component level as well, but I think it should not throw error on client level itself

Allow .off() on uninitialized channels

---

src/channel.js
src/client.js
test/channels.js
test/test.js
types/stream-chat/index.d.ts

[CHAT-790] support filter by custom data in search endpoint

---

src/channel_state.js

Avoid duplication of reaction, if it already exists in channel state
This is regarding optimistic updates to UI for reactions in our react sdks. We manually add reaction to channel state 
before sending it to server ([PR](https://github.com/GetStream/stream-chat-react/pull/180)). So when we receive `reaction.new` event for that new reaction, reaction is already present in the state. With this change, we will avoid the duplication of reaction.

Avoid duplicate reactions

---

types/stream-chat/index.d.ts

`Channel.update()` defines the `updateMessage` parameter as optional, and the underlying REST API allows it to be omitted as well. Fixed the TypeScript definition to allow the message to be omitted.

Fix TypeScript definition for Channel.update()

---

src/channel.js
test/channels.js

Make sure that when a non-member user opens a channel every message up to that point is marked as read. Previous implementation was trying something similar but did not really work.

better unread count for non-members

---

src/client.js
src/connection.js
src/token_manager.js
src/utils.js
test/connection.js
test/token_manager.js

```js
client.setUser({id: 'vishal'}, 'token');
```
```js
client.setUser({id: 'vishal'}, async () => {
// const token = await api.fetchToken();
return token;
});
```
- New class - `TokenManager`, which will be a common place to access token from for client and connection class.
- When ws connection fails with error code `40`, the token will be refreshed using tokenProvider function (given to `setUser` function) and connection request will be retried.
- When http request fails with error code `40`, the token will be refreshed using tokenProvider function (given to `setUser` function) and connection request will be retried.

Handling token expiration

---

src/connection.js

Feeld is facing some issue where ws just keeps waiting for close frame after manually disconnecting the ws. Its something we definitely need to fix on backend (as discussed with @thesyncim ). But we should not infinitely wait for it, in case there are delays. 
So forcefully resolving disconnection promise, if we don't receive close frame from backend within 2 seconds!

Forcefully closing the ws connection, if close frame gets delayed

---

types/stream-chat/index.d.ts
types/stream-chat/test-stream-chat.ts

Fixed TypeScript interface definition for Event to reflect actual types of `ChannelResponse` and `UserResponse` API response objects instead of the `Channel` and `User` classes.

Fix types for channel, member, and user values in Event interface

---

package.json
rollup.config.js
src/client.js
test/channel_permissions.js
test/channels.js
test/connection.js
test/delete_channel.js
test/gdpr.js
test/invites.js
test/moderation.js
test/multitenant.js
test/notifications.js
test/presence.js
test/query_users.js
test/reactions.js
test/serverside.js
test/test.js
test/threads.js
test/webhook.js
test/x-setup.js
types/stream-chat/api-response-tests/response-generators/channel-search.js
types/stream-chat/api-response-tests/response-generators/channel-type.js
types/stream-chat/api-response-tests/response-generators/channel.js
types/stream-chat/api-response-tests/response-generators/client.js
types/stream-chat/api-response-tests/response-generators/event.js
types/stream-chat/api-response-tests/response-generators/message.js
types/stream-chat/api-response-tests/response-generators/moderation.js
types/stream-chat/api-response-tests/response-generators/reaction.js
types/stream-chat/api-response-tests/response-generators/update-users.js
yarn.lock

bump uuid to v8

---

test/silent.js
test/token_manager.js

Reverts GetStream/stream-chat-js#329
Given version of UUID doesn't work well with react-native - https://github.com/uuidjs/uuid#getrandomvalues-not-supported

Revert "Fix uuid bump issues due to recent PRs"

---

src/channel.js
src/client.js
test/query_members.js
types/stream-chat/index.d.ts

**introduce a new endpoint that allows clients to filter and search channel members**
example queries:
query all the members for the current channel where user.name='tommaso'
```js
channel.queryMembers({'name':'tommaso'})
```
filter member by id
```js
channel.queryMembers({'id':'tommaso'})
```
query all the members for the current channel where user.name contains
```js
channel.queryMembers({'name':{"$q":'tomm'}})
```
query channel moderators
```js
channel.queryMembers({'is_moderator:true'})
```
query for banned members in channel
```js
channel.queryMembers({'banned:true'})
```

[CHAT-976] queryMembers

---

src/client.js

Force resolve wsPromise upon recovery

---

types/stream-chat/index.d.ts

This improves the types for the client `getConfig` method by making it more strictly tied to the channel configuration definitions itself.

Improve channel config types

---

package.json
test/webhook.js

Currently `channel.truncated` doesn't fire a webhook. I'm adding it and this is the related test.

Add test for channel.truncated webhook

---

test/presence.js

So this test works by creating an event handler. Then on each event we append that we got the event. After we get three events we then do the checking to make sure everything is what we expect.
The specific order we get events in changes as is expected for a concurrent program. Additionally we sometimes get extra events such as `notification.added_to_channel`. These events may have keys such as `channel`, but not have keys like `user`. If these events show up early enough, then we crash. By skipping these events we can increase the pass rate of tests.
This was debugged and fixed with the assistance of @gumuz and @vishalnarkhede.

Skip some events for the stopWatching test

---

src/client.js
test/moderation.js
test/query_users.js
types/stream-chat/index.d.ts

These changes add [expiration to user mutes](https://stream-io.atlassian.net/browse/CHAT-1006) to the api client. Backend implementation is described in [this pr](https://github.com/GetStream/chat/pull/1211).

Added mute expiration timeout to client

---

src/client.js
types/stream-chat/index.d.ts

To support expiration of user mutes, the api accepts an optional `timeout` parameter, defining the _expiration time in minutes_.
**note**: The signature of muteUser changed from: 
`muteUser(targetUserID, userID = null)`
to:
`muteUser(targetUserID, userID = null, options = {})`
In order to stay backwards compatible, the `options` parameter was added after the optional `userID`. 
This has the unfortunate effect that a call without a userID, but with a timeout  looks like this: `muteUser(1234, null, { timeout: 10 })`. I don't see a way around that.

Changed muteUser client method to include expiration timeout

---

package.json
src/client.ts
src/types.ts
ts-test/index.js
ts-test/response-generators/channel.js
ts-test/response-generators/message.js
ts-test/tsconfig.json
ts-test/unit-test.ts

I have added strict null checks to the tests to catch a few minor testing errors. Additionally I have corrected updateMessage input type. The backend will soon update to allow user objects to be used in mentioned users array, when this is done MessageBase can be changed to just Message and current Message type can be removed. The only field of messageResponse that is currently not an extension of Message is mentioned_users Message uses a string array, response a user array. Having these overlap 100% will also remove the need to map message response to message when updating a message.

add strict tests and correct message/null types

---

package.json
src/types.ts
ts-test/index.js

Add old types for backward compatibility
Add old types as helpers for backward compatibility and move production @types into non dev dependencies.

Add old helper types

---

src/client.ts
src/types.ts
ts-test/index.js
ts-test/response-generators/moderation.js

Adds typescript tests and corrects types for blocklist functions

add tests and correct types for BlockList

---

src/utils.ts

- Needed based on https://github.com/facebook/react-native/blob/0d02c60bae3025dee41874a88765dc872f401f45/Libraries/Network/FormData.js#L82

adding type key-value pair to FormData creation to fix React Native Android image upload failures

---

src/client.ts
src/types.ts
test/test.js

Flag options

---

src/channel.ts

`this._initializeState(state)` is already called in `channel.query` 
https://github.com/GetStream/stream-chat-js/blob/bug/duplicate-channel-initializeState/src/channel.ts#L1246

remove unnecessary _initializeState call in watch()

---

src/channel.ts
src/types.ts

make Channel.countUnread() ignore shadowed messages

[CHAT-1270] ignore shadowed messages in unread count

---

src/utils.ts
test/integration/test.js

apparently `FormData.append()` signature is different between the browser and 3rd party library we use for the node env, 3rd argument should only be `filename: string` 
similar to https://github.com/GetStream/stream-js/pull/393

fix #487: form data file name in browser

---

src/client.ts
src/connection.ts
src/types.ts
test/integration/ban_by_ip.js
test/integration/channels.js
test/integration/utils.js

This PR contains Ban by IP feature implementation.
I had to add some `X-Forwarded-For` trickery for IP manipulation, I would love to hear the feedback about this approach.
Also fixed a couple of warnings in `utils.js`
**Proposed Ban By IP API (Server-Side only):**
To ban user account and it's last known IP address you should provide `ip_ban: true` option to the `banUser` call:
```js
client.banUser(userToBan.id, {
user_id: adminUser.id,
ip_ban: true,
});
```
The unban procedure is unchanged:
```js
client.unbanUser(userToUnban.id);
```
When unbanning user who was banned by IP, IP will be unbanned even if there's another account who was using the same IP address.

[CHAT-1172] Ban by IP feature

---

src/types.ts

This PR fixes adds image_moderation_enabled field to AppSettings related types

Fix missing image_moderation_enabled field

---

src/client.ts
src/types.ts
test/integration/ban_by_ip.js
test/integration/moderation.js
test/integration/query_members.js
test/integration/serverside.js
test/integration/test.js
test/integration/webhook.js

Current versions of SDKs have very unclear way of executing a ban from server-side:
```
client.banUser('user1', {
user_id: 'user2'
})
```
Our customers struggle to understand the meaning of user_id field. This often leads to banning the wrong user account.
The new behavior will look like this:
```
client.banUser('user1', {
banned_by_id: 'user2'
})
```
This change is fully backwards compatible and will throw a warning if developer is still using "user_id" field.
This PR should only be merged after API update deployment

[CHAT-852] Add support for banned_by_id in ban methods

---

src/channel.ts
src/client.ts
src/types.ts
src/utils.ts
test/typescript/unit-test.ts
test/unit/utils.js

The tests need to be fixed as I didn't have time to look at them, I believe these should be the correct typings and I don't think the helper function needs to reside on the client. @mahboubii we need to discuss the allowed syntax though. Should it be that the sort takes a sort object or an array of sort object? or should it be 1:1 with the backend, where it takes a sort object or and array of {field, direction} objects?

Update sort types

---

src/channel.ts

There are some edgy cases with react components when message preview is added and gets updated after it's actually is sent. Few users are experiencing race condition when the actual event update the list before react is able to do so.

fix: duplicated new messages by current user

---

package.json
rollup.config.js
src/client.ts
src/utils.ts
yarn.lock

we don't really need cryptographically strong random values here, simpler implementation to support ReactNative/Expo apps.
clientID will look like this `firh1Xuozx1Q0UHUgUENp` instead of UUID format in API logs. 
[`nanoid/non-secure`](https://github.com/ai/nanoid/blob/master/non-secure/index.js) implemention : 
```js
// This alphabet uses `A-Za-z0-9_-` symbols. The genetic algorithm helped optimize the gzip compression for this alphabet.
urlAlphabet = 'ModuleSymbhasOwnPr-0123456789ABCDEFGHNRVfgctiUvz_KqYTJkLxpZXIjQW';
nanoid = (size = 21) => {
let id = ''
// A compact alternative for `for (var i = 0; i < step; i++)`.
let i = size
while (i--) {
// `| 0` is more compact and faster than `Math.floor()`.
id += urlAlphabet[(Math.random() * 64) | 0]
}
return id
}
```

replace uuid with nanoid

---

test/integration/invites.js

[CHAT-1411] make accept/reject invite a NOOP if the user is already accepted or rejected the invite

---

src/channel.ts
test/integration/query_users.js
test/integration/reactions.js

This PR adds `enforce_unique` optional parameter to `sendReaction`. When it's set to `true`, all existing user's reactions for the message will be overwritten by the new one.

[CHAT-1375] Add enforce_unique for sendReaction

---

src/types.ts
test/integration/webhook_before_message_send.js

The original change was made in #523. The corresponding API is going to be rolled back

[CHAT-1422] Rolled back webhook_id and webhook_failed message fields

---

src/client.ts

Field `user_details` is not used in `query_channels` API in any way. In cases when `this._user` field gets too large, application could experience performance issues.

Removed unused field from `query_channels`

---

src/client.ts

We added support for POST in the `queryChannels` API to address performance issues

[CHAT-1428] Switched queryChannels to POST

---

README.md
docs/userToken.md
src/types.ts
test/integration/ban_by_ip.js
test/integration/channel_permissions.js
test/integration/channels.js
test/integration/connection.js
test/integration/gdpr.js
test/integration/invites.js
test/integration/moderation.js
test/integration/multitenant.js
test/integration/notifications.js
test/integration/presence.js
test/integration/query_members.js
test/integration/query_users.js
test/integration/serverside.js
test/integration/slow_mode.js
test/integration/sqs_events.js
test/integration/sync.js
test/integration/test.js
test/integration/unique_usernames.js
test/integration/utils.js
test/integration/webhook_custom_commands.js
test/integration/webhook_push.js
test/typescript/response-generators/client.js
test/typescript/response-generators/moderation.js
test/typescript/unit-test.ts
test/typescript/utils.js
test/unit/client.js

We often copy-paste test code to implement new tests and with this we also increase the amount of incorrect/deprecated method calls.
This is what had been done in this PR:
1. Updated all `setUser` calls to `connectUser`
2. Updated all `updateUser(s)` calls to `upsertUser(s)`
3. Fixed extra `await` for `getTestClient` non-async calls
4. Fixed `connectUser` warning when running integration tests in CI
5. Removed deprecated and unused `webhook_id` and `webhook_failed` fields from `MessageResponse`

Cleaned up deprecated methods usages

---

src/channel.ts
src/channel_state.ts
src/types.ts
test/integration/messages.js
test/unit/channel_state.js

This PR adds support for `pinned_messages` property in channel state.
More about this feature in the docs: https://getstream.io/chat/docs/pinned_messages/?language=js

[CHAT-1516] Support pinned messages in channel state

---

test/integration/channels.js

1. Enable quoting messages in threads
2. Fix bug where updating a message could lead to an error when the quoted_message_id was left out
3. Make sure the quoted_message is enriched in the message.updated event

QA tests for quoted message improvements

---

src/client.ts
test/integration/channels.js
test/unit/channel.js

Fix member ordering for creating member based channels

---

src/client.ts
test/typescript/unit-test.ts
test/unit/client.js

Unfortunately Lots of TS boilerplates due to generics.
Potential Future improvements: `connectUser` can return the resolved promise for the second call instead of throwing an error if the user id in the token remains the same

[CJS3] client single instance

---

src/types.ts

adding types for translations

---

src/client.ts
src/token_manager.ts
test/integration/test.js
test/typescript/index.js
test/typescript/response-generators/client.js
test/typescript/response-generators/message.js
test/typescript/response-generators/moderation.js
test/typescript/response-generators/update-users.js
test/typescript/utils.js
test/unit/client.js

- `client.setUser()` function is removed in favor of `client.connectUser()`
- `client.setAnonymousUser()` function is removed in favor of `client.connectAnonymousUser()`
- `client.updateUser()` function is removed in favor of `client.upsertUser()`
- `client.updateUsers()` function is removed in favor of `client.upsertUsers()`
- `client._userAgent()` function is removed in favor of `client.getUserAgent()`

chore: rm deprecated functions

---

src/client.ts
test/typescript/unit-test.ts

add back deprecated aliases

---

src/channel_state.ts

In certain conditions, the channel messages array is reused, causing issues in React component logic ([related PR](https://github.com/GetStream/stream-chat-react/pull/724)). The proposed change clones the array.

Fix message mutation

---

src/channel_state.ts
test/unit/channel_state.js

There's a regression after we introduced `own_reactions` sync to `ChannelState`. This PR fixes it and simplifies some reaction-related code

Fixed message update in channel state

---

src/client.ts
src/connection.ts

CJS-7: Capitalise x-stream-client

---

src/client.ts

This PR follows from https://github.com/GetStream/stream-chat-js/pull/631 updating the way endpoints are passed via query params, as a list of comma-separated values on the same key.

Pass endpoints as comma-separated values

---

src/client.ts

`channel._disconnect` should only happen in `disconnectUser`, and not `closeConnection`. Because once you call channel._disconnect, it will be completely blocked of all the functionality. This issue was introduced in latest minor version. We need to think a bit more about this disconnect functionality, but for now to unblock react/react-native SDKs. This should fix it.

fix: moving channel._disconnect call from closeConnection to disconnectUser

---

src/client.ts

This fields is leaks into `updateMessage` which causes stale data in messages

Blacklist __html property in updateMessage

---

src/channel_state.ts
src/types.ts

- `message.__html` deprecated in favor of `message.html`

deprecate __html attribute on message

---

CHANGELOG.md
src/client.ts
test/unit/channel.js
test/unit/channel_state.js
test/unit/client.js

Slack discussion - https://getstream.slack.com/archives/C01FT5767AS/p1615968119001100
Updating pinned message fails, if there is mentioned_users in message. This is something missed in react sdk, (to ensure conversion of array of user objects to user ids). I think its better we handle it on js client as well.
- Extra check to see if `message.mentioned_users` is array of string or objects
- Convert array of user objects to array of user ids.
- Unit tests for the change

Ensure mentioned_users is array of user_ids. in updateMessage

---

src/channel.ts
src/client.ts
test/unit/channel.js

- Slack discussion: https://getstream.slack.com/archives/C01FT5767AS/p1616153988038900
- Added access to unsubscribe handler from `channel.on` function.

Return unsubscribe handler from `channel.on`

---

src/client.ts

It is not currently possible to set custom https agent, although documentation of `StreamChat` constructor says otherwise:
```ts
* @param {httpsAgent} [options.httpsAgent] - custom httpsAgent, in node it's default to https.agent()
```

Allow to override https agent

---

src/channel_state.ts
test/unit/channel_state.js

Because the client sets `received_at` as a Date type (src/client.ts#L1168) and `ChannelState#clean()` was expecting a string, it hasn't been working at all. A better fix might be to restrict the Event typing to Date since it is never a string after being handled by the client, but in lieu of that we'll handle both types here and add a test.
- Fix ChannelState#clean() to properly clear stale typing events

Fix ChannelState#clean() to handle received_at as Date type

---

test/typescript/response-generators/channel.js

This "fixes" a test that started failing recently, due to a backend change. However, I'm not sure what the intent of the test was and if it's still valid like this.
Tagging you @nhannah since you were the author of the test

fixed response test for frozen update channel

---

src/types.ts

Match the setting and return type for field enforce_unique_usernames to a union type instead if string.

update type for enforce_unique_usernames

---

src/client.ts
src/types.ts

This PR adds a new method for sending custom event to a user. 
It also adds a new `UserCustomEvent` type which is used in the new method.
⚠️ This shouldn't be merge until the API integration
- Add `UserCustomEvent` type
- Add `sendUserCustomEvent` method

[CHAT-1558] Add sendUserCustomEvent method

---

src/client.ts
src/types.ts

added queryMessageFlags method

---

src/client.ts
src/signing.ts
src/types.ts

- `createToken` add support to have `iat` claim while generating tokens.
- added `revokeTokens()` method to revoke/unrevoke tokens on an application level.
- added `revokeUserToken()` method to revoke/unrevoke tokens on user level.
- added `revokenUsersToken()` method to revoke/unrevoke tokens for multiple users at once.

[CHAT-1650] Add user, application level token revoke helpers and iat claim in tokens

---

src/channel.ts
src/client.ts
test/typescript/utils.js
test/unit/channel.js

https://getstream.slack.com/archives/C0185U214TF/p1620718706190100
We didn't consider muted channels while incrementing unread count, when new message comes in. We shouldn't increase unread count if channel is muted.

CRNS-352: Unread counts and muted channels

---

src/client.ts
src/connection.ts
src/utils.ts

Adding a retry interval between two consecutive API calls, the logic is same as in case of web-socket connection retrial added the same kind of behaviour on API calls as well.

Add retry backoff on client API calls

---

src/channel_state.ts

This is the client-side fix to retained pinned messages after a channel is truncated

CHAT-1828: clean pinned messages after channel truncation

---

src/types.ts
test/typescript/index.js

quoted_message had usage issues due to recursive referencing on the generics. This should fix that.

change quoted_message type to not be recursive

---

src/channel.ts
src/permissions.ts
src/types.ts

This PR adds support for new `setRoles` operation in `UpdateChannel` API.
Also, did some refactoring around repetitive UpdateChannel SDK calls
UPDATE: renamed `setRoles` to `assignRoles` after discussion with the Product Team
UPDATE 2: switched format of `assignRoles` to object-based

[CHAT-1851] Add `assignRoles` method to Channel

---

src/types.ts
test/typescript/response-generators/moderation.js

This PR updates type tests for permissions and also adds some missing fields to permission types

Fix tests for Permission related APIs

---

src/channel.ts
src/client.ts
src/types.ts
src/utils.ts
test/unit/channel.js
test/unit/client.js

Updates the `channel.search()` and `client.search()` endpoints to support pagination using a next value and sorting parameters. For example: 
```js
// get a page of sorted results
const page1 = await client.search(
{ cid: my_cid }, 
'search text', 
{ limit: 100, sort: [{ relevance: -1 }, { updated_at: 1 }, { my_custom_field: -1 }]  });
// Query the second page of results. The same sort order will be used as in your first query, so there's no need to include it
const page2 = await client.search(
{ cid: my_cid }, 
'search text', 
{ limit: 100, next: page1.next });
// Pagination backwards by using the returned `previous` value
const page1Again = await client.search(
{ cid: my_cid }, 
'search text', 
{ limit: 100, next: page2.previous });
```
-

[CHAT-1814] Updates to message search

---

src/client.ts
src/types.ts

This PR switches pinMessage to use `partialUpdateMessage` and also adds support for server-side message pinning

Use partial message update for pinMessage

---

src/client.ts

We already have the information in the route, we can remove it from the payload.

Remove target user id from payload on sendUserCustomEvent

---

src/types.ts

Fix typing for results_warning, which can be null
-

Allow results_warning to be null

---

src/channel.ts
src/channel_state.ts
test/unit/channel.js

Add remove quoted messages logics

---

src/client.ts

Delete event for channel is not currently handled by our js client. So adding the event handler for it.
- Remove the channel from `activeChannels` list, once the channel is deleted.

CRNS-311: Handling channel.deleted event

---

src/client.ts
src/types.ts
src/utils.ts

When user gets updated on backend, the event handler for event `user.updated` doesn't take care of properties which were removed. Purpose of this PR is to remove such deleted properties from `client.user` and `client._user` object.

CRNS-317: handling deleted properties of user

---

src/client.ts

- Once client receive `channel.deleted` or `notification.channel_deleted`, we remove it from `client.activeChannels`. But this prevents channel listeners to be called for that event. So we should only remove it from activeChannels after listeners have been fired.

Fixing delete channel logic

---

src/client.ts

This PR is meant to fix the concurrency problems we are having in the React Native SDK side. It basically adds a new parameter to our queryChannels function in order to avoid initializing specific channels so we can use it to ignore active channels that would take care of their own state.

Add new skipInitialization option when calling queryChannels

---

src/client.ts
src/types.ts

optional flags for export channels: this one requests delete message text to be overwritten (by default).

Clear text in export

---

src/types.ts
test/typescript/response-generators/moderation.js

On the backend we are implementing proper support for `condition` field for custom permissions. This PR aims to synchronize API with the new version.
This is a breaking change, but since permissions v2 is yet to be released and `condition` feature for custom permissions is undocumented, I suggest we only bump minor version with appropriate release note

[CHAT-2260] Change Permission.Condition type

---

src/channel.ts
test/unit/channel.js

Reference - https://stream-io.atlassian.net/browse/CRNS-406
Reference Issue - #739 
Files changed are:
- src/channel.ts
- test/unit/channel.js

fix: exclude system message from unread count

---

src/client.ts
src/types.ts

[CHAT-1823] Add async deleteChannels endpoint

---

src/connection.ts
src/types.ts

refactor: connection logger

---

src/client.ts
src/connection.ts
src/insights.ts
test/unit/connection.js

refactor: simplify StableWSConnection constructor params

---

src/client.ts
src/types.ts

This adds 'quoted_message' to the list of reserved fields and excludes it from the payload when updating a message.
- [fix] Fixes 400 API errors when updating messages with quoted messages.

Fix update message

---

src/channel.ts
src/client.ts
src/types.ts

This PR adds support for new `getPinnedMessages` endpoint as well as enables to update `pinned_at` of the message.

Support new pinned messages endpoint

---

src/client.ts
src/types.ts

- Do not require user_id in _queryFlagReports

Do not require user_id for queryFlagReports

---

src/channel.ts

prevent own_capabilities and hidden from being set to undefined after a channel.updated event is fired
link to issue: https://github.com/GetStream/stream-chat-react/issues/1310

fix: prevent own_capabilities and hidden set to undefined

---

src/client.ts
src/types.ts

[CHAT-2049] Add async user export endpoint support

---

src/channel.ts
src/channel_state.ts
test/unit/channel.js

Currently, we unset `channel.state.read.userId.unread_messages` on `message.read` and `message.new` if the message is sent by the current user. This PR adds `unread_messages` as 0 for both of those events to keep consistency in the read state object.
It also adds typing of `unread_mesages`.
- `unread_messages` will now be set to `0` rather than omitted following the `message.read` event, and the `message.new` event when the message is sent by the current user.

fix: include unread_messages for all message events

---

.github/workflows/lint.yml

According to the [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request), `on: [pull_request]` is triggered on `opened`, `synchronize` and `reopened`. This adds `edited`, so it can rerun if you edit the title of your PR
-

build: rerun PR title lint when PR is edited

---

src/client.ts
src/types.ts

feat: imports API endpoints

---

src/types.ts

This PR involves adding the `file_size` and `mime_type` as keys to the Attachment type.
- Adding the `file_size` and `mime_type` as keys to the Attachment type.

refactor: add file_size and mime_type keys to attachment type

---

src/channel.ts
src/types.ts
test/unit/channel.js

If the read events are turned off on the application, then the unread count shouldn’t show up on the channel list component. Currently, when a new message comes in, we increment the unread count for a particular channel. But this increment works even if read events are turned off, which leads to confusing behavior.
- Add the logic for not incrementing channel unread count if the read_events are off.

fix: unread count to not increment if channel has read_events off

---

src/client.ts
test/unit/client.js

When we use the markAllRead method, we get the event notification.mark_read, which updates the total_unread_count, but not the channel.state.unreadCount. This PR solved the above issue.
- Added the logic to set the activeChannel state's unreadCount to 0.
- Added tests for the same.

fix: channel unreadCount to be set as 0 when notification.mark_read event is dispatched [CRNS - 433]

---

src/token_manager.ts
test/unit/connection.js

When providing a `tokenProvider` function to `connectUser`, if the `tokenProvider` promise is rejected this will result in an uncaught promise rejection.
This fix adds a `try/catch` around the `await`ing of the user provided `tokenProvider` function as to gracefully handle the error.
- fix: catch tokenProvider rejection

fix: catch tokenProvider rejection

---

.github/workflows/type.yml
src/types.ts
test/typescript/utils.js

- Fixed the typescript for push config
- Added missing types for `automod_threshold`
- Added missing types for `reminders `
- Move the api keys and secrets for typescript test to github secret

fix: added missing push and reminders related types 

---

src/channel_state.ts
test/unit/channel_state.js

UI SDKs (for example Angular and React) create a message preview before sending a message request to the API and display those message previews in the message list while the message is being sent. There was a bug in the channel state where thread reply preview messages weren't added to the channel state. This was due to the recent jump to message functionality.
- fix: thread reply preview not added to channel state

fix: thread reply preview not added to channel state

---

src/client.ts
test/unit/client.js

Add additional check before setting unread count for all active channels to 0. Check that the `notification.mark_read` event has `unread_channels: 0`.

fix: handling of notification.mark_read event

---

src/client.ts

Back to back calls to `client.openConnection` without awaiting results into multiple websocket connections.
Reproducible scenario occurs within RN SDK:
- Add Chat component on multiple screens (channel list screen, channel screen, Thread screen etc)
- Chat component adds [AppState](https://reactnative.dev/docs/appstate) listener to app
- [client.closeConnection](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Chat/hooks/useIsOnline.ts#L30) upon backgrounding the app
- [client.openConnection](https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Chat/hooks/useIsOnline.ts#L42) upon foregrounding the app
- Put the app in background and bring it back to foreground which results into AppState listeners being fired …

fix: multiple ws connections due to redundant openConnection calls

---

src/client.ts

This is breaking but no one uses this endpoint yet, safe then.

fix: rename sendAt field to scheduledFor

---

src/client.ts
src/types.ts

This PR adds a new type `TestCampaignResponse` to expose either the campaign (on success) or invalid user if there is any.

fix: add TestCampaignResponse type

---

src/client.ts
src/errors.ts
src/types.ts
test/unit/errors.js

Add type definitions for error API response payload and for error generated and thrown on error response propagated from the chat client.
This is important for SDKs that use the stream-chat client in order to facilitate work with errors thrown by the client.

refactor: add type for general error API response format

---

src/types.ts

This PR adds the type of `thumb_url` for the response returned when a video file is uploaded to Stream CDN. The `thumb_url` is the URL of the thumbnail of the video generated and sent by the backend.
- Added `thumb_url` to `SendFileAPIResponse` types.

fix(types): added support for thumb_url for video attachments in send file response

---

src/channel.ts
src/channel_state.ts
test/unit/channel.js

Calling `channel.truncate` with `truncated_at` option would remove all of the messages within the channel state completely disregarding this option - added fix which removes messages up to specified timestamp as stated [in the documentation](https://getstream.io/chat/docs/node/truncate_channel/?language=javascript).

fix(Channel): add "truncated_at" to "channel.truncated" event handler 

---

src/channel.ts
test/unit/channel.js

Extends #991 `truncated_at` functionality for `pinnedMessages`.

fix: pinnedMesages truncated_at aware

---

src/types.ts

- Add `cdn_expiration_seconds` to the App settings

feat: add `cdn_expiration_seconds` to the App settings

---

src/client.ts
src/connection.ts
src/types.ts
test/unit/client.js

- Fixed the following issue:
```
QueryChannels failed with error: "Watch or Presence requires an active websocket connection, please make sure to include your websocket connection_id"
```
- Fixed handling of multiple client.openConnection calls

fix: race of query channels and ws connection

---

src/client.ts
test/unit/client.js

if apn certificate exists, update app settings mutates given parameters

fix: do not mutate settings param

---

src/channel_state.ts

This change allows the SDKs to increase the size of the messages loaded when jumping, thus avoiding multiple requests to the db.
`loadMessageIntoState` accepts an optional `limit` parameter, (default value is 25)
-

feat: support limit for load message into state

---

src/channel.ts
src/channel_state.ts
src/client.ts
src/connection.ts
src/events.ts
src/types.ts

Purpose of this PR is to add changes to make it possible for UI SDKs to implement offline support.
- Added support for `persistUserOnConnectionFailure` option on client. Current we unset user and userId property if `client.connectUser` call fails and we expect customer to call connectUser again to retry. To implement offline support for UI SDKs, we need to persist user and userId even if connectUser fails.
- Added `staticState` option for Channel constructor, which represents if the channel has been initialized using static set of messages, members, read etc.
- A new local event has been introduced 'channels.queried', to let UI sdks know that one or more channels have been queried. This event will be emitted from `client.queryChannels()` and `channel.query()` calls. Payload of this event …

feat: changes to support offline feature

---

src/client.ts
src/types.ts

it has some breaking changes but this API had been marked as to be changed.

feat: campaign missing pieces

---

src/channel.ts
test/unit/channel.js

Currently, if you unwatch a channel and then watch it again, only members that were already present in channel state and new members added to the channel will be updated in the channel state. Users that have been removed between unwatching and rewatching will stay in the channel state.
This PR aims to solve that, and with that fix #988

fix: don't keep removed users when reinitializing channel

---

src/client.ts

This PR exposes a method to create an abort controller for the next HTTP request. The API is not the most intuitive, but it brings no changes to the existing API. 
- Expose a method `createAbortControllerForNextRequest` to create and associate an abort controller with any HTTP request performed by the client.

feat: support cancelling http requests

---

src/channel.ts
src/client.ts
src/types.ts

Channel configurations can differ from channel to channel so storing configurations under `channel.type` causes overrides for other loaded channels.
Channel `A` of type `messaging` for user `john` with channel role `channel_moderator` has different set of commands in the channel configuration than the channel `B` of type `messaging` where `john` isn't a `channel_moderator`. As channel `B` is after channel `A` in the list and is of the same type, the configuration gets overriden and `john` isn't able to see available commands for channel `A`.
I find using `channel.cid` as the most appropriate store key as the configuration should be bound to user/channel. I might be missing something so I'd like you guys to share your opinions (especially RN team).

fix: update client to use channel.cid as config keys

---

src/types.ts

Fixes [improperly specified](https://github.com/GetStream/stream-chat-js/pull/974/files) call related types. Property `options` of type `CreateCallOptions` doesn't specify what the object should look like and I couldn't find anything in the [REST documentation](https://getstream.io/chat/docs/rest/#other-createcall-request) so I typed it as uknown record for now.

fix: replace String types with string, define options as UR

---

src/types.ts

Add missing optional property `joined` to `ChannelResponse` type.
Fixes: #850

fix: add missing property "joined" to ChannelResponse type

---

src/channel.ts

Changes to support optimistic DB update - https://github.com/GetStream/stream-chat-react-native/pull/1758
2nd param to function `addMessagesSorted` determines weather messages being added may already exist in state or not. If they already exist, that means they were optimistically added, but timestamp of the message needs to be updated with the one stored on backend.

feat: allow optimistically added messages in local state

---

src/channel.ts
src/types.ts

Following PR fixes two issues:
https://github.com/GetStream/stream-chat-react-native/issues/1570 `message_id` param in `markRead` api should ideally mark the channel as read until that message. But this feature was never implemented on backend, so its better to drop it from typescript.
_This is not from customer, but we noticed while investigating previous issue. But could possibly fix long standing https://github.com/GetStream/stream-chat-react-native/issues/148_
When we receive `message.read` event, we use the `received_at` as a timestamp as `last_read` (time at which user corresponding to event last read the channel). But `received_at` is [generated on client side](https://github.com/GetStream/stream-chat-js/blob/master/src/client.ts#L1044) using `new Date()` constructor. So if user's …

fix: read event handling and markRead api params

---

src/channel.ts

When we received a new message, we only update `unread_messages` for the current user. But not for other members of channel. This PR updates unread_messages for all the members of channel by incrementing it by 1.
Source of issue discussion - https://getstream.slack.com/archives/CML3HAEJW/p1669389073043739

fix: update unread_messages when new message is received

---

src/client.ts
src/types.ts
test/unit/client.js

```ts
const client = StreamChat.getInstance('key', 'secret', {
axiosRequestConfig: {
headers: {
'Cache-Control': 'no-cache',
Pragma: 'no-cache',
},
},
});
```

feat: option to set axios config

---

src/channel.ts

We extended the Send Message endpoint to receive an optional `force_moderation` _bool_ parameter, in order to provide option for enforcing moderation on server side sent messages. 
https://github.com/GetStream/stream-services/issues/1181
-  Add `force_moderation` option field in the sendMessage() request

feat: extend SendMessage to server-side moderation API

---

src/client.ts
src/signing.ts
test/unit/signing.js

- Current API accepts strings only in place of `requestBody` while it is should be possible to send instance of a `Buffer`, .e.g while using [firebase functions's requests](https://firebase.google.com/docs/reference/functions/firebase-functions.https.request.md#httpsrequestrawbody). 
This PR fixes it by changing accepting both strings and Buffers. 
- PR adds missing JSDoc for `verifyWebhook`.
- PR patches[ timing attack vulnerability](https://security.stackexchange.com/questions/83660/simple-string-comparisons-not-secure-against-timing-attacks) by using `timingSafeEqual` instead of simple string comparison.
- Adds some unit tests
- Fix invalid param type of `verifyWebhook`

fix: change invalid param type of verifyWebhook and patch security issue

---

src/channel.ts
src/channel_state.ts
src/types.ts

receive last_read_msg_id from server
also populate last_read_message_id
To create a QA test on the chat project, I needed this library to return a new property. 
Corresponding pull request in chat: https://github.com/GetStream/chat/pull/4930
- `ReadResponse` now includes `last_read_msg_id` received from server.
- `last_read_message_id` is added to type `ChannelReadStatus`.

feat: receive last_read_message_id from server

---

.github/CODEOWNERS
src/client.ts
src/types.ts
test/typescript/index.js

```js
const client = StreamChat.getInstance('key');
client._setToken({ id: 'vishal' }, 'my_token');
const response = await client.getUnreadCount();
```
```js
const client = StreamChat.getInstance('key', 'secret');
const response = await client.getUnreadCount('vishal');
```

feat: api endpoint for unread count

---

SECURITY.md
src/channel.ts
test/unit/channel.js

Start updating the channel members state when `user.banned` and `user.unbanned` events are delivered. This is needed in order the SDKs can react to changes in the client state.

feat: reflect user ban events in channel members state

---

src/channel.ts
src/types.ts
test/unit/channel.js

feat: added 'pending' property to message

---

src/channel_state.ts

- [ X ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
When `message.deleted` event was delivered, the client code invoked `channelState.removeQuotedMessageReferences(event.message);`. This function was converting  `created_at, pinned_at, updated_at` values of each quoting message to string using `toString()` method. That lead to truncation of milliseconds from each timestamp. Later the truncated timestamps distorted the decision logic in `ChannelState._addToMessageList()` in the following way,
1. the last message B in the list was also quoting another message A
2. the quoted message was deleted (timestamps of message B now truncated)
3. the message B was then …

fix: prevent truncating message timestamps when updating references to deleted quoted message

---

src/types.ts

[According to the JS SDK documentation](https://getstream.io/chat/docs/javascript/silent_messages/?language=javascript), the `Message` object passed as the first argument to `Channel.sendMessage()` method should optionally carry `silent` property. This property was however not declared in the type definition. This PR adds the property  to the underlying `MessageBase` type definition.

fix: add missing property 'silent' to MessageBase type

---

src/client.ts

made _unblockMessage method public and kept alias for backwards compatibility

feat: make unblockMessage method public

---

src/types.ts

The message object return in API response now contains a new field `deleted_reply_count`

feat: add field deleted_reply_count to MessageResponseBase

---

src/channel.ts
src/client.ts
src/types.ts

Types are used by stream-chat-react.

feat: declare and export types SendMessageOptions and UpdateMessageOptions

---

src/client.ts
test/unit/channel.js

The `client.channel()` method did not handle correctly `client.channel(type, undefined, channelData)` calls. Instead of trying to find channel by members it directly returned a brand new `Channel` instance. Also it tried to get channel by id, if id was explicitly set to `undefined`.

fix: handle getting channel by members with channel id explicitly undefined

---

src/client.ts
src/types.ts

This reverts commit 5700abdb072e41c23e4439b8fb01eafd1993d5e8.
`getUnreadCount` is required in backend QA tests.
-

fix: Revert "fix: remove unused unread count api endpoint #1143"

---

src/client.ts
src/utils.ts
test/unit/utils.js

**Fixes**: https://github.com/GetStream/stream-chat-react-native/issues/2235
On iOS 17, all the `get` requests which involve object or array in url params (e.g. `queryMembers`) are failing.
In iOS 17, NSURLs are now encoded according to RFC 3986 standards (as specified in https://www.ietf.org/rfc/rfc3986.txt), whereas they used to adhere to RFC 1738/1808 standards in earlier versions.
reference: https://developer.apple.com/documentation/foundation/nsurl/1572047-urlwithstring
> For apps linked on or after iOS 17 and aligned OS versions, [NSURL](https://developer.apple.com/documentation/foundation/nsurl) parsing has updated from the obsolete RFC 1738/1808 parsing to the same [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) parsing as …

fix: axios param serializer to comply with RFC 3986

---

src/channel.ts
src/events.ts
test/unit/channel.js
test/unit/channel_state.js

A channel is flagged as `initialized` only after `channel.query` call successfully returns inside `channel.watch()` method. The WS events for a given channel can however arrive sooner to the client than `channel.query` call returns. Processing WS events before the `channel.query` call returns leads to checking whether the channel has been initialized. If the channel was not flagged as initialized, then the code throws error.
To prevent processing WS events before the initialization has finished, this PR introduces a WS event queue for a channel. There will all the event objects be gathered until the channel is flagged as initialized. Once flagged as initialized, the queue is flushed.

fix: queue channel WS events until the channel is initialized

---

src/channel.ts
test/unit/channel.js
test/unit/utils.js

Currently `channel.lastRead()` throws an error if a channel is uninitialized.  Call to `channel.countUnreadMentions()` would throw an error in such case too. This complicates the work in an UI with uninitialized `Channel` instance which is a valid use-case. This PR proposes to return valid values like 0 for unread mentions count and `null` for last read data and not to break the UI.

fix: evaluate channel.lastRead when channel is not initialized

---

src/utils.ts
test/unit/utils.js

fixes: https://github.com/GetStream/stream-chat-react-native/issues/2257
params with undefined values need to be excluded from param serialization logic, since stream backend doesn't treat `undefined` same as param not being present.

fix: undefined values in query params

---

src/channel.ts
src/events.ts
test/unit/channel.js
test/unit/channel_state.js

The `channel.deleted` event marks a channel as disconnected, but then other arriving channel events on the server-side cannot be executed, because `Channel.getClient()` throws an error for disconnected channel. The client is being accessed within `Channel._isInitialized()` method that was invoked for each incoming channel event.  As we do not have immediate solution for this, we are reverting the queuing of channel WS events. The next step is to decide, whether channel events listeners should be executed for disconnected channel. 
This reverts commit 2073579e

Revert "fix: queue channel WS events until the channel is initialized"

---

src/client.ts

When a user was updated the client didn't update the user reference in `channel.state.read` object.
-

fix: update user reference in channel read data

---

src/client.ts

Post the V1 axios upgrade, if an integrator uses [axios interceptors ](https://axios-http.com/docs/interceptors)
whatever content type we pass to sendFile method is not used. Instead it uses ` "Content-Type": "application/x-www-form-urlencoded",`
This caused broken image/video uploads for a customer using RN SDK. 
In this change, we move to using postForm method instead of post to default to `Content-Type: multipart/form-data`
- RN TS sample
- React Vite sample

fix: use postForm instead of post for sending files

---

src/client.ts
src/types.ts

fix: add default contentType as multipart/form-data in sendFile

---

src/client.ts
src/types.ts
test/unit/client.js

Adjust `deleteUsers` to match [the documentation](https://getstream.io/chat/docs/react/update_users/?language=javascript&q=pruning#deleting-many-users);
- adds missing `pruning` option to enums
- adjusts conditions
- makes `options` truly optional
- adds tests

fix: deleteUsers - add `pruning` to options enums

---

src/channel.ts
src/channel_state.ts
src/events.ts
src/types.ts
test/unit/channel.js

Upon receiving the new `notification.mark_unread` event update:
- channel read state for "author" of the event
- update channel's `unreadCount` property
A new property added to the `ChannelReadStatus` is `first_unread_message_id` which basically is an indicator whether the channel has been marked unread. The property is undefined for `message.new` events.
With the above state updates, the SDK can implement the feature of marking messages in a channel as unread.

feat: handle notification.mark_unread

---

src/types.ts

Added new types for moderation responses, and a new optional property `moderation_details` on `MessageResponse`.
When the message doesn't pass moderation and is bounced, the response from POST `/channels/:type/:id/message` endpoint contains `moderation_details`. The clients may use this field to properly notify users.
The types are based on 
https://github.com/GetStream/chat/blob/master/automod/moderation/nnbb.go#L61-L66, since they are not exposed in OpenAPI.
- new optional property `moderation_details` in `MessageResponseBase` type

feat: add moderation types

---

src/channel.ts
test/unit/channel.js

A user's unread count for a channel is not reset on the back-end when:
1. the user sends a new message
2. a thread reply is received
3. message.new event for own message is received
Therefore neither the client should reset the unread count to 0. Keeping the logic that resets the count to 0 in the above cases would mean that if I channel is marked unread and one of the above actions happen (we receive a thread reply), then the channel unread count would locally be reset to 0, but on the BE it would be kept non-zero.

fix: prevent channel unread count reset to 0 when sending message and on new own or thread messages

---

src/channel.ts

fix: allow user_id in keystroke and stopTyping function

---

src/types.ts

- fix: add missing `in$` operator for `teams` filter in `queryUsers`

fix: add missing in$ operator for teams filter in queryUsers

---

src/channel.ts

The `markRead` and `markUnread` calls should be available on server-side, but a client-side permission check made it impossible to call them before. This PR fixes that.
After the merge these calls will work on server-side:
```
const channel = streamClient.channel(
"<channel type>",
"<channel id>"
);
channel
.markRead({
user_id: "<user id>",
})
.then(console.log)
.catch(console.error);
channel
.markUnread({
message_id: "<message id>",
user_id: "<user id>",
})
.then(console.log)
.catch(console.error);
```
- fix: markRead and markUnread can be called from server-side

fix: markRead and markUnread can be called from server-side

---

src/client.ts

Fixes an issue where apps would crash due missing state on undefined channel when trying to update `userChannelReferences`.
Error in question:
```
TypeError: Cannot read properties of undefined (reading 'state')
node_modules/stream-chat/dist/browser.es.js at line 6861:31
_defineProperty(this, "_updateUserMessageReferences", function (user) {
var refMap = _this.state.userChannelReferences[user.id] || {};
for (var _channelID2 in refMap) {
var _channel3 = _this.activeChannels[_channelID2];
var state = _channel3.state;
/** update the messages from this user. */
state === null || state === void 0 ? void 0 : state.updateUserMessages(user);
}
});
```

fix: skip updateUserMessageReferences if channel is undefined

---

src/types.ts

Adds support for a new optional message field `message_text_updated_at` that contains the timestamp of the last time the message text was edited.

feat: add message edited timestamp

---

src/client.ts
src/types.ts

This allow the optional query parameter `show_deleted_message` in API `getMessage` in order to show text of deleted msg.

feat: add support for show_deleted_message in `getMessage`

---

src/channel.ts
src/client.ts
src/events.ts

This adds support for calling a new undelete endpoint, which can be used for undeleting previously soft deleted messages. The API requires this to be called from serverside clients and will return a 403 if called from the browser.
The API will also publish a new `message.undeleted` event when the message has been undelete. I'm not sure if more changes are required here beyond adding it to the event map.
- Add `undeleteMessage` for bringing back soft deleting messages

feat: add a way to undelete a deleted messages

---

src/channel.ts
src/client.ts

Few weeks ago we received a [GH issue](https://github.com/GetStream/stream-chat-react/issues/2306) where integrator mentions, that muting a channel with unread count `> 0` will reset unread count to zero - while that is not the case, the issue they described further still stands and that is when the state gets actually reset (upon unmuting said channel) and the page is reloaded (re-query the channels), the unread count is back where it was prior to muting/unmuting.
This PR removes condition from unread counting function and removes state resetting in the `notification.channel_mutes_updated` handler. That way when the channel is unmuted the unread count represents actual value which would match the one received from the channel when re-queried.
__Circle back once applicable__:
Adjust …

fix: align unread counting on muted channel

---

src/client.ts
src/types.ts

- `ChatClient.closePoll(...)`
- `ChatClient.addPollAnswer(...)`
- `allow_user_suggested_options` to query filters

feat: (polls) support closePoll, add/fix missing fields

---

src/types.ts

This adds new field in `MessageResponse` that represents a map of reactions for that msg.
As a key you have the type ('like', 'love') and as value some useful information for building a better UI.

feat: add reactiongroups in `MessageResponse`

---

.lintstagedrc.json
src/types.ts
src/utils.ts
test/unit/utils.js

Adds fallback for the new `reaction_groups` property on messages.
Since `reaction_groups` will not be available for older messages, we use the data from `reaction_counts` and `reaction_scores` to provide reactions data in a similar shape as a fallack.
The `reaction_groups` property is marked as optional.

feat: add reaction groups fallback

---

src/types.ts

According to the [implementation](https://github.com/GetStream/chat/blob/master/utils/mq/reaction/reaction.go#L38-L53), reactions filter only supports the following fields:
- user_id
- type
- created_at
So no need to include any other keys in the filter type. Adding all other keys from the `Reaction` type breaks the filter type, because `Reaction` type is overridable via generic params.
Also, adds pagination `next` field to response.

fix: fix filter type for query reactions

---

src/channel.ts
src/types.ts
src/utils.ts

- https://www.notion.so/stream-wiki/User-level-control-of-real-time-indicators-4e4391269bfe4b3daa5cbec9bee83a77#3f877afa1f644d5285ea4b65d4954a0e
- [AppConfig](https://github.com/GetStream/stream/pull/5632) (**MUST be merged first**)
- [Backend](https://github.com/GetStream/chat/pull/6269)
- https://www.notion.so/stream-wiki/User-Control-Privacy-API-Spec-ef9da87f88084e5ca9e764567fd16c78

feat: support privacy settings

---

src/types.ts

Backend PR - https://github.com/GetStream/chat/pull/6400
Jira ticket: https://stream-io.atlassian.net/browse/PBE-1872

feat: member_limit option on queryThreads and getThread endpoint

---

src/channel_state.ts
src/types.ts
test/typescript/index.js
test/typescript/unit-test.ts

We had a separate type for `channel.membership` which seemed to be incomplete and different from the type of `channel.members[i]`.
In this PR:
1. Replace ChannelMembership type with ChannelMemberResponse everywhere, since it's supposed to be the same type (see backend types: [[1]](https://github.com/GetStream/chat/blob/master/controllers/chat/v1/payload/channel.go#L46-L47) and [[2]](https://github.com/GetStream/chat/blob/master/types/channel_member.go#L261)).
2. Keep ChannelMembership for reverse compatibility, but deprecate it and make it an alias for ChannelMemberResponse.

fix: fix channel.membership type

---

src/client.ts
src/types.ts

Add support for querying message histories.
-

feat: [PBE-1666] add query message histories

---

src/channel.ts
src/channel_state.ts
test/unit/channel.js

Update quoted message references on message.updated and message.deleted events.

fix: update quoted message references on message.updated and message.deleted events

---

src/client.ts
src/types.ts

- Should add a support to the flag feedback endpoint that will allow users to "review" a flagged message from the React SDK client.
-

feat: add support for the update flag endpoint

---

src/client.ts
src/index.ts
src/moderation.ts
src/types.ts

- https://stream-io.atlassian.net/browse/PBE-5101
- https://getstream.slack.com/archives/CE5N802GP/p1719839445504719
All the moderation v2 endpoints have been moved to client.moderation umbrella. Basically if you want to use moderation v2 flagging:
```tsx
await client.moderation.flagUser(...)
await client.moderation.flagMessage(...)
await client.moderation.muteUser(...)
await client.moderation.queryReviewQueue(...)
```

feat: moderation v2 endpoints under client.moderation

---

src/client.ts

Any DOM element with an id can be accessed from the window object by `window.{EL_ID}`.
Also, global variables are available without chaining window object. e.g. 
`variableName // global variable` is the same as `window.variableName`
Therefore if a page contains a DOM element with id "process" the client constructor check `typeof process !== "undefined"` is not sufficient. `process.env.ANY_ENV_VARIABLE` will throw the TypeError `TypeError: process.env is undefined` that crashes the messenger.
- Implemented additional check for process.env object.

fix: handle issue with process and DOM conflict

---

src/client.ts
src/index.ts
src/thread.ts
src/thread_manager.ts

Just splitting a large file in two for easier navigation.
Also, removed throttling from `throttledHandleConnectionRecovery` here, mostly to avoid imports, but also because it's not a correct way to deal with this async method. More fixes to this method are coming in further PRs.

chore: thread and thread manager into separate file

---

src/thread.ts

Cleaning up types a bit:
1. State when `Thread` is initialized without an underlying `Channel` is not very useful. Now threads always have a channel.
2. Storing `channelData` separately is excessive, we have it in `channel`.
3. `staggeredRead` removed for now, it's supposed to make a triumphant return at some point.
This will break ThreadProvider in React SDK, fixed in a follow-up PR.

feat: do not store channelData in thread state

---

README.md

Running `yarn link` and then following the steps mentioned in the `README.md` did not particularly do the trick for the React Native CHAT SDK specifically. There is also the required step of adding the path towards the `stream-chat-js` directory to the `resolver.extraNodeModules` object under the `stream-chat` key.
- Added the extra step to our `README.md` file

fix: add an extra step after yarn link for the RN setup

---

src/channel.ts

fix: declare channel.lastMessage return value type as possibly being undefined

---

package.json
src/thread.ts
src/thread_manager.ts
test/unit/threads.test.ts

Notable changes:
- Removed throttling from all subscriptions, should work properly without any throttling.
- Fixed handling read states (see `subscribeNewReplies` and `markAsRead`). Got rid of the `incrementOwnUnreadCount` - it's now part of a more generic update performed on `message.new`.
- Fixed a bug caused by typo in pagination logic.
- Updated most tests. Replaced spying on methods (which tests implementation details) with checking resulting state.
- Added tests for pagination logic.
- All tests for Thread are now green.
- Either fixed TODOs that were fixable, or removed TODOs that we are not going to get to any time soon.
Don't expect green CI in this PR. These changes are in a separate PR so that reviewing is at least feasible :)

fix: fix most TODOs and tests for Threads class

---

src/channel.ts
src/thread.ts
test/unit/threads.test.ts

Previously, `Thread` instance created an unitized `Channel` instance for the parent channel. The idea was that when the thread is rendered, it will be rendered inside the `Channel` component which will take care of initializing the instance.
However, it makes sense to expect at least _some_ data in this channel instance: its name and members. This data is available in the thread response which is used to construct a `Thread` instance.
So now we try to hydrate the channel instance with whatever data we have. This fixes at least one known bug: channel names were not rendered in thread list view unless channel was previously queried.
Before:
After:

fix: hydrate channel instance from thread response

---

src/utils.ts

The refactor of the `addToMessageList` function made in #1330 contained an unfortunate error which prevents adding a message to an empty message list.
See:
- https://github.com/GetStream/stream-chat-js/pull/1330/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351L331-R388
- https://github.com/GetStream/stream-chat-js/pull/1330/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R397-R399

fix: adding message to an empty message list

---

src/thread.ts

🚂 #1354 
An empty members list should also be used to hydrate a thread's channel. One case when empty members list is meaningful is requesting with `member_limit: 0`.

fix: allow hydrating thread's channel with an empty members list

---

src/thread_manager.ts
test/unit/threads.test.ts

There is currently a weird behaviour on the thread query-ing endpoint in the backend where if you call it with `{ limit: 0}` it skips the pagination entirely and returns all of the threads. While things aren't initialized yet, it is entirely possible that both `threads.length` and `unseenThreadIds.length` are `0`, hence the issue occurring (typically on the first ever load of the thread list).
This PR takes care that this doesn't happen and the `limit` is never `0`.
-

fix: initial load threads edge case

---

src/client.ts
test/unit/channel.js

This PR solves an issue where whenever custom data is being passed to an already existing channel, `channel.data` would be overwritten rather than merged with the custom data. This makes sure that this situation doesn't happen and that the channel is kept in tact regardless of what we passed.
-

fix: merge custom data with current one rather than override

---

src/utils.ts
test/unit/threads.test.ts
test/unit/utils.test.ts

This regression has been introduced with the refactor of the function in question in #1330. Tests have been built on previous version of this function and applied to a new version with a fix. This PR also fixes a test case in `threads.test.ts`.

fix(addToMessageList): prevent messages shifting when adding reactions

---

src/channel.ts
src/types.ts

This adds support for archiving and un-archiving channels, similar to https://github.com/GetStream/stream-chat-js/pull/1378 for pinning.
- Add `channel.archive()` and `channel.unarchive()`
- Update typescript types for `queryChannels` to support pinning and archiving filter & sort options

feat: add support for archiving channels

---

src/moderation.ts
src/types.ts

feat: moderation endpoints for query and delete config and check api

---

src/channel.ts
src/events.ts
src/types.ts

https://linear.app/stream/issue/CHA-334/add-ai-related-user-events
https://www.notion.so/stream-wiki/Q4-AI-use-cases-1386a5d7f9f680958001f1c382ec6f12
https://github.com/GetStream/chat/pull/7612
- `ai_indicator.update`
```json
{
"type": "ai_indicator.update",
"cid": "messaging:general-3ac667a1-6113-4b16-b1e3-50dbff0ffb89",
"channel_id": "general-3ac667a1-6113-4b16-b1e3-50dbff0ffb89",
"channel_type": "messaging",
"message_id": "aba120c6-c845-4c5a-968d-31ed0429c31e",
"ai_state": "AI_STATE_ERROR",
"ai_message": "something went wrong",
"user": {
"id": "ai-1e9666df-9b9e-429e-b7e4-e2f54446d5ac",
"role": "user",
"created_at": "2024-11-27T15:51:55.649597Z",
"updated_at": "2024-11-27T15:51:55.649597Z",
"last_active": "2024-11-27T15:51:55.668787Z",
"banned": false,
"online": true
},
"created_at": …
```

feat: add AI related user events

---

src/channel.ts
src/types.ts

- https://linear.app/stream/issue/CHA-365/missing-thread-participants-data-in-streamio-query
- https://github.com/GetStream/chat/pull/7674
Enable the `Channel.search` to enrich `thread_participants` in found messages.
-

fix(search): missing thread_participants in message

---

src/campaign.ts
src/types.ts

- https://github.com/GetStream/chat/pull/7756
-

feat: support CampaignSenderMode

---

src/client.ts
src/events.ts
src/thread.ts
src/types.ts
test/unit/threads.test.ts

- ~allow querying thread-related data as pure objects instead of instances of `Thread` class~ (discarded)
- handle `thread.updated` within `Thread` class and consider custom fields
`Thread` class now handles custom data by sifting through `ThreadResponse` keys, skipping reserved ones and storing custom keys with associated data within `ThreadState.custom` object.  For type support, declaration file has to be created and `ThreadResponseCustomData` has to be extended:
```ts
// yourFile.d.ts
import 'stream-chat';
declare module 'stream-chat' {
interface ThreadResponseCustomData {
myCustomProperty: string;
myOtherCustomProperty: { meta: Array<{ key: number }> };
}
}
```
When the `Thread` is instantiated, the custom properties can be accessed from the state:
```ts
const thread = await …
```

feat(threads): handle custom data

---

src/types.ts

- Add team to review queue filter types

fix: add team to reviewqueue filter types

---

src/channel.ts
src/client.ts
src/types.ts
src/utils.ts

Add support for push preferences at the user and member/channel level. 
@oliverlaz can you help me wrap this up? (not entirely familiar with your workflow and project setup)
@tbarbugli fyi

feat: push preferences

---

src/constants.ts
test/unit/channel.js

The message set, when initiated, should receive pesimistic pagination indicators, meaning that it should expect there is no more data to load. This is of course adjusted with the first channel(s) query. It is logical, that in order the message list that paginates over messages to be showed, first the channel data has to be queried.

fix: make initial message pagination state pesimistic

---

.github/workflows/lint.yml
src/types.ts

This PR is adding private messaging for a select list of users in a channel. If the user who sends the message has the `CreateRestrictedVisibilityMessage` permission, then by adding `restricted_visibility: [ 'john', 'jane' ] would limit the visibility of that message to only john and jane. The other members of the channel can't see the message. The sender of the message can always see it.

[CHA-403] Private messaging

---

.github/workflows/lint.yml

Repository `stream-chat-js` serves to publish JS library `stream-chat` that follows the semver versioning. This is the standard for the public libraries. In order to be able to follow semver versioning, the developers need to know, whether the merged PRs represent features, chores, fixes etc. Based on that the developer that performs the new version release actually calculates the next version number. 
Removal of linter, that controls the PR title compatibility with [conventional commit rules](https://www.conventionalcommits.org/en/v1.0.0/) leads to:
- confusion to those that release the library
- the automation process that builds the changelog
- confusion to the integrators that read the commit history
- sabotage for future automation of the whole release process
For integration to …

chore: return linting CI

---

src/channel.ts
src/client.ts
src/poll_manager.ts
test/unit/poll_manager.test.ts

This PR fixes a case of overwriting the poll cache when we should not do that. Essentially, hydrating all messages in `messageSet.messages` whenever `channel.query` is invoked does 2 things:
- Takes in all of the new messages and hydrates the cache with them (they do not exist in the cache yet)
- Also takes in the old messages, which were used as a basis to paginate on top of and rehydrates the cache with them (they already existed in the cache before)
The problem here is; since we do not update `message.poll` objects at all, but rather use them as an ID reference towards the cache - these polls are stale (since they're retrieved from the stale state and not as an HTTP response). The state is then overwritten with the stale data until we query all messages again.
The bug is particularly …

fix: improper poll state overwrite

---

src/channel_manager.ts
src/utils.ts
test/unit/channel_manager.test.ts
test/unit/utils.test.ts

There was an unfortunate bug with the pagination logic in the new `ChannelManager` that somehow evaded me in the last PR. The offset was not being calculated properly, particularly in cases where:
- We might have `state.channels` receive updates from something other than pagination (WS events for instance) and it will then contain either broken pagination or duplicate values when actually paginating (for example if a WS event arrives as the query is being executed)
- The state might also change since there's nothing from preventing it (`setChannels` is `public`)
- Any other case really between 2 `loadNext()` invocations
For this purpose, when running the queries we always calculate the offset through `state.channels.length` and we make sure to run `state.getLatestValue()` as late as …

fix: premature channels state consumption in ChannelManager

---

src/index.ts

Angular SDK needs to `setChannels` in case of
- reselecting previous active channel after reconnect
- `addChannel`, `removeChannel` methods
-

fix: export promoteChannel

---

src/client.ts
src/types.ts
test/unit/client.js

fix: add extra user agent fields resolvable by react native

---

src/connection.ts
test/unit/connection.js

With the recent changes to the user agent resolution within our LLC, encoding the uri component properly during building the WS url was missed. This works just fine if you're already connected, however it will fail if you're trying to connect another user.
In the current state of the LLC it would only affect React Native as the other SDKs do not yet add the extra params. 
-

fix: properly encode user agent on WS connection

---

src/client.ts
src/types.ts
test/unit/client.js

Whenever using the `updateMessage` API, we rely on updating the entire message object with most of its values left unchanged and only some of them mutating. This generally works fine as the backend does updates in a smart way (i.e it won't update a field if its value hasn't changed). However, since natively Javascript dates go down to milliseconds and server-side they are stored until microseconds, there is a discrepancy between these 2 values and the `pinned_at` value is considered different; hence causing things to malfunction.
For example, if a user does not have pinning permissions in a specific channel and someone else pins a message, they won't be able to update it due to the fact that it will be considered as an update to the `pinned_at` date as well - throwing an error. Similarly …

fix: remove pinned_at from the updateMessage api

---

src/index.ts

- [] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [] Code changes are tested
When removing generics from stream-chat-angular I had an issue where augmenting the same custom interface (for example `CustomChannelData`) from two places (SDK and sample app) some changes were ignored (detailed description: https://getstream.slack.com/archives/C06CF5TKRGA/p1741163343794659).
Found this open GH issue for TypeScript: https://github.com/microsoft/TypeScript/issues/46617 
https://linear.app/stream/issue/ANG-31/drop-generics 
-

fix: multiple module augmentation fails in Angular

---

src/types.ts

Property `image` is considered a regular property according to the OpenAPI specification.

fix: add image property to UserResponse type

---

src/client.ts
src/types.ts

BREAKING CHANGE: `ErrorFromResponse` class constructor now requires second parameter (`status`, `response` and optionally `code`)

fix: adjust ErrorFromResponse error class

---

src/client.ts
src/connection.ts
src/types.ts
test/unit/connection.js

fix: provide a way for a suffix to be added to wsUrl

---

src/moderation.ts

- Added a new endpoint for moderation `checkUserProfile`
- Have added clear warning in description that this is subject to introducing breaking changes.
- Backend PR: https://github.com/GetStream/chat/pull/8424

feat: user profile check endpoint

---

src/client.ts
src/types.ts

The `options` parameter of the `StreamChat.queryDrafts` method required a `sort` type which when sent to the BE wouldn't work - it needs to be normalized before sending.

fix: [CHA-826] normalize queryDrafts sort

---

src/campaign.ts
src/types.ts

- https://linear.app/stream/issue/CHA-214/handle-hidden-channels-as-part-of-campaigns
Introduce a new `show_channels` flag to let campaigns show the hidden channels.
-

feat: add show_channels flag to campaigns

---

src/campaign.ts

- https://linear.app/stream/issue/REACT-346/missing-event-related-fields-when-creating-campaigns
Add `skip_push` and `skip_webhook` params to campaign creation call.
-

fix: add event fields on creating campaign

---

src/channel.ts

Creating a new endpoint /channels/{type}/{id}/member for partially updating members, this endpoint is functionally the same as /channels/{type}/{id}/member/{id} (which is now deprecated). The user id is automatically provided for clientside request, so it doesn't make sense to have it as a mandatory field in the url path. The new endpoint optionally accepts ?user_id=...
At some point we must sunset the deprecated endpoint

[CHA-855] - Refactoring partial update member

---

src/channel.ts
test/unit/channel.js

Event handler for `member.updated` receives a `member` object which contains `archived_at` and `pinned_at` with `null` values if unarchive/unpin actions are called - to make matters for our integrators easier, the only nullish value for these would be `undefined`. I'll keep the types unchanged (#1515) as the `ChannelMemberResponse` used in the `Event` type is still correct.

fix: [REACT-353] unify pinned_at & archived_at nullish values

---

src/messageComposer/attachmentManager.ts
src/messageComposer/linkPreviewsManager.ts
src/messageComposer/middleware/pollComposer/state.ts
src/messageComposer/middleware/pollComposer/types.ts
src/messageComposer/middleware/textComposer/mentions.ts
src/messageComposer/textComposer.ts
test/unit/MessageComposer/middleware/pollComposer/state.test.ts
test/unit/MessageComposer/textComposer.test.ts

Resolve the last bugs before releasing the MessageComposer feature

fix: remove message composer bugs

---

src/client.ts
src/constants.ts
src/types.ts
src/utils.ts

Update fails if the payload contains both `user` object and `user_id`property.
```
StreamChat error code 4: UpdateMessage failed with error: "cannot set both message.user and message.user_id."
```

fix: add user to RESERVED_UPDATED_MESSAGE_FIELDS

---

src/messageComposer/middleware/pollComposer/state.ts
src/messageComposer/middleware/pollComposer/types.ts
src/messageComposer/pollComposer.ts
test/unit/MessageComposer/middleware/pollComposer/state.test.ts

Allow to inject errors generated outside the PollComposer state middleware chain so that platform native data (browser event data) can be reflected in platform agnostic manager state. 
Close REACT-371

feat: allow to inject errors to during PollComposer field updates

---

src/client.ts
src/types.ts
test/unit/client.test.js

This PR allows `client.queryChannels` to optionally return the raw response and not run hydration at all (and subsequently not provide an array of `Channel` instances).
It is meant to be used generally server-side so that integrators can have access to other fields not available in a `Channel` instance. It should resolve [this Zendesk ticket](https://getstream.zendesk.com/agent/tickets/64585). 
We can probably keep it the same api if we use discriminated unions, but I feel like it'd complicate things further for no good reason. Keeping the apis separate made sense to me.
-

fix: add optional raw queryChannels api response

---

src/messageComposer/middleware/messageComposer/compositionValidation.ts
test/unit/MessageComposer/middleware/messageComposer/compositionValidation.test.ts

Loading UI with empty message composition, then creating draft (type text, leave to another channel and get back) and trying to send the message would prevent message from being sent. The reason was that the composition workflow validation required at least one local edit.
Closes REACT-383

fix: allow to compose non-empty message from draft without local edits

---

src/messageComposer/middleware/pollComposer/state.ts
test/unit/MessageComposer/middleware/pollComposer/state.test.ts

Currently the options are added when the last option has some text. But when the new option added is reordered, there is no way to add a new option. To improve this, the new behaviour is to add new option when all of the option fields are filled.

fix: add new poll option only when all of the current options are filled

---

src/channel_manager.ts
src/messageComposer/attachmentManager.ts
src/messageComposer/configuration/types.ts
src/messageComposer/messageComposer.ts
src/poll.ts
src/poll_manager.ts
src/store.ts
src/thread.ts
src/thread_manager.ts
src/utils/WithSubscriptions.ts
test/unit/MessageComposer/messageComposer.test.ts

Introduces private `WithSubscriptions` abstract class as a base for all of our new entities.

refactor: general code cleanup (Threads/Polls/MessageComposer)

---

src/messageComposer/attachmentManager.ts
src/messageComposer/fileUtils.ts
test/unit/MessageComposer/attachmentManager.test.ts

The goal of the PR is to upsert attachments only when they exist. This is especially important because on React Native, we allow cancelling uploading by calling removeAttachments, but when the upload still happens, the upsert proceeds. We will only update you if the attachment is present.
The other fix is that the `FileList` is not supported on RN. Thanks to @MartinCupela for a prompt suggestion on this issue.

fix: upsert attachmemts only when attachment exist and handle FileList for react native

---

src/messageComposer/messageComposer.ts

Newly introduced helper `WithSubscriptions` abstract class provides a pre-defined `unregisterSubscriptions` method which needs to be in this form (not arrow function) for devs to be able to use it with `super` keyword. This obviously means that `this` has to be bound to it when used as standalone function as `this` means something else entirely when it's not attached to an object (or attached to a different object). Rookie mistake, my apologies. Thank you @khushal87 for spotting this issue.
Marked as `chore` as to not pollute changelog with unreleased broken stuff.

chore: fix MessageComposer.registerSubscriptions

---

src/utils/mergeWith/mergeWithCore.ts
test/unit/utils/mergeWith.test.ts

Closes REACT-402
Trying to merge objects from source to undefined, null or scalar target lead to infinite loop in mergeWith util. Breaks initiation of middleware that allows for custom searchSource

fix: override target scalar, null and undefined values with mergeWith

---

src/channel.ts
src/client.ts
src/offline-support/offline_support_api.ts
src/offline-support/types.ts
test/unit/offline-support/offline_support_api.test.ts

Unfortunately, with the latest offline support rework the types of all queueable actions were broken to be `T | undefined` instead of `T`. 
This PR addresses that, by forcing `queueTask` to throw if execution fails just like any of our HTTP apis would.
-

fix: broken api return values and types

---

src/token_manager.ts
tsconfig.json

This is a backport of https://github.com/GetStream/stream-video-js/pull/1812 - see there for details.
- Errors (rejections) thrown from `client.connectUser()` will have `cause` attached in some cases with an original error that caused token to fail to load.

fix: attach original token provider error as cause to loadToken rejection

---

src/messageComposer/messageComposer.ts
src/messageComposer/middleware/messageComposer/MessageComposerMiddlewareExecutor.ts
src/messageComposer/middleware/messageComposer/cleanData.ts
src/messageComposer/middleware/messageComposer/userDataInjection.ts
src/poll_manager.ts
test/unit/MessageComposer/messageComposer.test.ts
test/unit/MessageComposer/middleware/messageComposer/userDataInjection.test.ts

This PR does a couple of things:
- Removes `messageComposer.pollComposer.initState()` from the `createPoll` api
- This is being done because we both do not yet know if the composer should clear the state or not; especially if sending the message fails or the creation dialog gets closed with a delay (while the HTTP requests finish)
- Introduces a new middleware for injection of `user` data from the `client` for each `localMessage`
- This serves as an enriched optimistic update for messages, since the `user` was missing for polls as the middleware chain quits earlier than that
- An optimistic update for poll creation
- We now populate the `poll_manager`'s cache whenever we create a poll so that by the time the optimistic update for the poll message arrives we already have the data in the …

fix: poll composer improvements

---

src/messageComposer/messageComposer.ts
src/utils/WithSubscriptions.ts
test/unit/MessageComposer/messageComposer.test.ts

Stack-based cleanups don't work with components as components may dissapear from the view at any point in time, ref counting is a better approach to this problem.
Co-authored-by: Ivan <@isekovanic>

fix: use ref counting in WithSubscriptions abstract

---

src/channel.ts
src/messageComposer/messageComposer.ts
src/offline-support/offline_support_api.ts
src/offline-support/types.ts
test/unit/MessageComposer/messageComposer.test.ts
test/unit/offline-support/MockOfflineDB.ts
test/unit/offline-support/offline_support_api.test.ts

The goal of the PR is to handle offline support for draft messages and also allow composing a message when the composition is not empty when the offline DB is enabled. Thanks to @isekovanic for the help with the offline support explanation here.
-

feat: handle offline support for drafts

---

src/reminders/ReminderManager.ts
test/unit/reminders/ReminderManager.test.ts

Keep the value up-to-date from a central place.

fix: propagate stopTimerRefreshBoundaryMs to all reminder timers on ReminderManager config update

---

src/messageComposer/messageComposer.ts
test/unit/MessageComposer/messageComposer.test.ts

This PR fixes an issue where `draft`s containing a `quotedMessage` were never cleared from the `messageComposer` state unless manually deleted.
The easiest way to reproduce this is to:
- Create a `draft` that contains a quoted message
- Make sure the draft is there on the server (reload or whatever suits best)
- Send the draft message from whichever SDK is being used
- Reload the app again
- The draft will still be there and no matter how many times we send it it is never going to be removed
The reason this happens is [this check](https://github.com/GetStream/stream-chat-js/blob/7dcf10dd4f5234fbc228409222d003e90f6a020d/src/messageComposer/messageComposer.ts#L298), which is used to determine whether a draft should be deleted on pretty much all `state` listeners in the `messageComposer`, …

fix: properly delete drafts with quoted messages

---

src/poll.ts
test/unit/poll.test.js

Fix REACT-515
Prevent removing the oldest casted vote if trying to vote over the `max_votes_allowed` limit. Instead publish a notification that can be rendered by the UI components.

fix: handle poll vote limit trespass with notification instead of removing the oldest vote

---

src/types.ts

feat: add channel message count response fields

---

src/types.ts

In the current configuration, we must provide all hook configs in the event_hooks parameter of the UpdateApp API. This approach can lead to accidental hook deletion if we don't include existing configs in the request.
Providing full CRUD endpoints would be overkill. The simplest solution is to introduce an explicit marker in the request that indicates when a webhook should be deleted. We can use the existing update app API’s event_hooks parameter and mark delete: true when users want to remove a specific config.
The behavior would work as follows:
- If the id doesn't exist in the request, create the hook
- If the id exists in the request, update the hook in the DB. If the DB record doesn't exist, create a hook with the provided id
- If "delete": true exists in the request, delete the hook …

feat: explicit event_hooks deletion

---

src/utils.ts
test/unit/channel.test.js
test/unit/client.test.js

When upgrading our Stream packages at Glue, we noticed that our quoted messages were displaying the same `created_at` date and time as the messages they were attached to after the upgrade. After some debugging we isolated the issue to the upgrade, and after looking further, noticed that the code that converts `MessageResponse` to `LocalMessage` - i.e. `formatMessage` in `src/utils` - was referencing the original message in `toLocalMessageBase` rather than the `msg` passed to it, which would cause the issue we are seeing.
- Updated `message` references in `toLocalMessageBase` to `msg`
- Updated tests to correspond with this change

fix: formatMessage - reference the correct msg in toLocalMessageBase

---

src/channel.ts
test/unit/channel.test.js

Reflect the `blocked` property value from WS events to Channel data.

feat: update channel's blocked property on channel.hidden and channel.visible events

---

package.json
scripts/bundle.mjs
yarn.lock

Upgrade `axios` to `v1.12.2` and externalize packages that were previously bundled with the client.

fix(bundle): upgrade axios and externalize previously bundled packages

---

src/messageComposer/messageComposer.ts
test/unit/MessageComposer/messageComposer.test.ts

Currently, if you listen to client notifications on your app and move from channel screen to thread screen. This will trigger the notification if a draft is not present for a parent message id as `this.channel.getDrafts` would error out. Ideally, this should be gracefully handled without showing a client-side notification. This has been fixed in the PR.

fix: do not add error to client notifications for getDrafts
